/* The provenance check runs before this document is written, so the supplement
 * is gated the same way the manuscript is. */
require("child_process").execFileSync(process.execPath, [__dirname + "/check_numbers.js"],
  { stdio: "inherit", cwd: __dirname });

const d = require('docx');
const {Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel} = d;
const fs = require('fs');
const NUM = JSON.parse(fs.readFileSync("/home/claude/repo/analysis/out/numbers.json","utf8"));
const PR=NUM.primary||{}, NS=NUM.nested||{}, TW=NUM.threeway||null,
      TN=(NUM.threeway_nested&&NUM.threeway_nested.colon)?NUM.threeway_nested:null,
      CV=NUM.converge||null, TIE=NUM.ties||null, FXD=NUM.fixedn||{},
      OVC=(NUM.overlap||{}).colon||null;
const f=(x,k=3)=>(x===null||x===undefined||!isFinite(x))?"—":Number(x).toFixed(k);
const f0=x=>f(x,0); const pct=(x,k=1)=>(x===null||x===undefined||!isFinite(x))?"—":(100*Number(x)).toFixed(k)+"%";
const C=PR.colon||{}, R=PR.rott||{};

const body=[]; const add=(...x)=>x.forEach(e=>Array.isArray(e)?body.push(...e):body.push(e));
const P=(t,o={})=>new Paragraph({spacing:{after:o.after??96,line:264},
  alignment:AlignmentType.JUSTIFIED,
  children:[new TextRun({text:t,size:o.size??21,font:"Calibri",italics:o.i,bold:o.b,color:o.color})]});
const H1=t=>new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{before:250,after:120},
  children:[new TextRun({text:t,font:"Calibri"})]});
const Q=t=>new Paragraph({spacing:{before:200,after:80},indent:{left:340},
  border:{left:{style:d.BorderStyle.SINGLE,size:12,color:"9DB2C6",space:12}},
  children:[new TextRun({text:t,size:20,font:"Calibri",italics:true,color:"3A4A5C"})]});
const W=t=>add(P(t,{size:19,color:"55606B",after:190}));

add(new Paragraph({spacing:{after:60},children:[new TextRun({
  text:"Response to the seventh review",bold:true,size:30,font:"Calibri"})]}));
add(P("Manuscript: What data-driven relaxation of trial eligibility criteria can and cannot promise: an out-of-sample evaluation, and why reliability was not determined by cohort size alone across the mechanisms examined",{size:20,color:"555555",after:250}));

add(P("The first comment is the sharpest statistical criticism this paper has had, and it is right. Our nested bootstrap resamples an estimator built on a small number of inner splits, not the estimator we report as the point, so its percentile interval carries the inner Monte Carlo variance on top of the population variance. We had noticed the symptom — " + (NUM.threeway_nested && NUM.threeway_nested.max_gap ? "the two runs disagree by up to " + f(NUM.threeway_nested.max_gap,2) : "the two runs disagree visibly") + " — and reported it, but we did not draw the conclusion, and we let a sentence stand in Text S1.6 saying the two could not disagree at all. Both cannot be true and we should have seen that.",{after:250}));

add(H1("Major comments"));

/* 1 */
add(Q("1. The three-way interval and point estimate are not the same statistic; the bootstrap replicates a much noisier estimator."));
add(P("Accepted in full. Raising the inner split count to match the point estimate is linear in that count and would take roughly twenty times the compute this analysis already uses, which we do not have. We have therefore done what the comment offers as the alternatives, and taken the consequence for the claims."));
add(P("First, what kind of difference this is. Each of these quantities is an average over independent splits, so the split count changes the variance of the estimator and not its expectation: the estimator the bootstrap resamples is a noisier version of the reported statistic, not a different statistic. That is worth stating plainly, because it is what makes the problem a variance problem and so addressable by deflation rather than a bias problem, which would not be."));
if (CV) add(P("Second, the evidence. Supplementary Table S1e reports, for six representative quantities on the colon cohort, the behaviour of the split-count estimator at " + CV.counts.filter(c => c < Math.max.apply(null, CV.counts)).map(f0).join(", ") + " splits and at each design's own full run. Our first version of this table gave only the implied Monte Carlo standard deviation s over the square root of R, and the reviewer would have been entitled to object that this is an identity once s is fixed. The table now also reports an observed quantity: the long run is cut into disjoint blocks of R consecutive splits, each block giving an independent R-split estimate, and the standard deviation and mean of those block estimates are reported beside the implied value. In the columns with enough blocks to mean anything the observed spreads run from about seven tenths to about one times the implied ones — where the implied value is the larger, deflation removes more variance than the data show, which is why the raw interval is always printed beside the deflated one — and the block means do not move with R, which is the empirical form of the statement in the previous paragraph. The exact per-split calculation also checks the bootstrap: at its own inner split count the exact Monte Carlo standard deviations agree with the estimates the bootstrap forms internally from the within-resample variance to within " + (CV.vs_internal ? f(CV.vs_internal.max_diff,3) : "\u2014") + " across " + (CV.vs_internal ? f0(CV.vs_internal.rows.length) : "\u2014") + " quantities. That agreement is what licenses the deflation, and we would not have offered the deflation without it."));
add(P("Third, the interval itself. Tables S3 and S3c now give two intervals for each quantity, where the second is estimable: the raw percentile interval, and the same interval after deflating the inner Monte Carlo component out of the spread by the ratio of the outer-sampling to the total standard deviation. The deflation is an approximation resting on the same additive-variance assumption as the decomposition, and it is shown alongside the raw interval rather than in place of it. For some quantities the estimated inner variance is at least the total spread, so the subtraction returns a non-positive outer variance and no deflated interval can be formed; those show a dash rather than a zero-width interval. The tables distinguish the two ways that happens, because they mean opposite things: a quantity that barely moves across resamples has little spread to decompose, while one that moves a great deal between inner splits can have its whole across-resample spread accounted for by the inner term. The lowest-hazard-ratio dominator in Table S3c is of the second kind, and the Results and the table now say its raw interval reflects inner-split noise rather than patient-level sampling."));
add(P("Fourth, the endpoints. We now compute the Monte Carlo error of the 2.5% and 97.5% endpoints themselves by resampling the outer replicates, so a reader can see how far the tails are determined by a handful of draws. This is reported in the note to Table S3 and, in a row of its own, in Table S3c \u2014 the table drawn from the smaller outer count, and so the one where the comment applies most. With the outer counts we can afford, the endpoints are not well determined and should be read to one decimal at most."));
add(P("The table covers colon and six quantities rather than all of them, which is what the compute allowed; the deflation applied to the Rotterdam intervals rests on the variance decomposition and on the agreement reported above, not on a Rotterdam convergence run."));
add(P("Fifth, and this is the part that matters for the claims: we have not established the coverage of this nested procedure against a known population, and the Shapley sign step is a non-smooth model-selection step for which we would not assume nominal coverage. The abstract and Methods now say the intervals are approximate, that they carry inner Monte Carlo variance and that their coverage is not established, and the paper treats them as indicating the order of the uncertainty rather than as calibrated inference. We would rather say that than leave a reader to assume otherwise."));
add(P("On the wording, “confirmatory” is withdrawn. Block (b) is now described as the quantity evaluated on patients that took no part in choosing the comparator, and the text says explicitly that this is an internally validated sample-split estimate addressing selection optimism, not a confirmatory result in an independent cohort, since the same patients recur across splits. The capitalised label in the supplement is gone. The Text S1.6 sentence that contradicted Table S3c has been rewritten to say what actually happens."));
W("Where: analysis/split_converge.R (new); analysis/export_numbers.R (deflated intervals, endpoint Monte Carlo error); Methods; Results §1; Supplement Tables S1e, S3, S3c and Text S1.6.");

/* 2 */
add(Q("2. The currency comparison cannot support “equally” or “indistinguishable”."));
add(P("Accepted. Binning sixteen scenarios into quartiles of each currency and averaging the within-bin standard deviation is a descriptive summary over sixteen rows a bin, with no uncertainty attached and three outcomes computed on the same scenarios. It cannot establish equivalence and we should not have written as though it did."));
add(P("The abstract now says the descriptive dispersion measure was similar for the three currencies in these sixteen scenarios, and no longer says “equally”. The Results carry the same qualification and point at the new table."));
add(P("New Supplementary Table S2c reports the comparison in full, which the supplement never did: the bin edges for each currency, which scenarios fall in which bin, the within-bin standard deviations, the number of bins used and the exact aggregation to the three summaries" + (FXD.spread_patients ? " of " + f(FXD.spread_patients,3) + ", " + f(FXD.spread_events,3) + " and " + f(FXD.spread_ess,3) : "") + ". We were wrong to say the unconditional comparison was in Table S2b; it was not there, and it is now in S2c."));
if (FXD.currency_diff) add(P("We have also attached uncertainty to the difference, which was missing. Each scenario contributes one row per fitting size, so the resampling unit is the scenario; the observed differences are " + f(FXD.currency_diff.events_minus_patients,3) + " for events minus patients and " + f(FXD.currency_diff.ess_minus_patients,3) + " for effective sample size minus patients, and a cluster bootstrap over the " + f0(FXD.currency_diff.n_clusters) + " scenarios gives intervals [" + f(FXD.currency_diff.ci_events[0],3) + ", " + f(FXD.currency_diff.ci_events[1],3) + "] and [" + f(FXD.currency_diff.ci_ess[0],3) + ", " + f(FXD.currency_diff.ci_ess[1],3) + "]. Both contain zero and both are wide, which is the honest summary: this design does not separate the currencies, and cannot show them equivalent either. One detail is stated in the table because it would otherwise look like an error: the quartile edges are recut inside each bootstrap replicate, which shifts the within-bin spread, so the bootstrap means differ from the observed differences and here fall on the other side of zero. The point estimates are the observed differences and the bootstrap supplies only the intervals."));
W("Where: Abstract; Results §3; Supplement Table S2c.");

add(H1("Minor comments"));
add(P("1. “Confirmatory” is withdrawn throughout the manuscript and the supplement, as described under comment 1. The earlier response letters keep their original wording; they are the record of what was said at the time, and the build’s provenance check reports them as exempt on every run for that reason."));
add(P("2. The Uncertainty and implementation paragraph opened with an unconditional “Intervals are bias-corrected and accelerated bootstrap intervals”. It now reads “Interaction and Shapley intervals are …”, so it cannot be read as covering the whole paper."));
add(P("3. The RMST-rule direction is rephrased as the reviewer suggests. Both quantities are probabilities of improvement over the full protocol, and the text now says the probability of a greater restricted mean difference is higher for the RMST-selected variant while the probability of a lower hazard ratio is lower for it, which removes the reading that it achieved a better hazard ratio."));
add(P("4. The title is narrowed again, to the reviewer's wording: “… and why reliability was not determined by cohort size alone across the mechanisms examined”."));
add(P("5. Accepted, and the matrix is now printed. New Supplementary Table S1f gives the full correlation matrix of the nine eligibility indicators for each cohort, as a lower triangle; Table S1 keeps the largest absolute off-diagonal value as a summary and points at S1f. Pointing a reader at a script in a repository was not an adequate answer when the repository link is not yet live."));
if (TIE) add(P("6. The comparator set excludes the rule's own subset and all comparisons are strict, so an exact tie counts against the rule. We asserted this was negligible without measuring it; new Supplementary Table S1d measures it. In colon, " + f(TIE.colon.tie_frac_hr,5) + " of matched comparators tie the rule exactly on the hazard ratio" + (TIE.rott ? " and " + f(TIE.rott.tie_frac_hr,5) + " in Rotterdam" : "") + ", so reversing the convention would move the matched proportions by about that fraction at most. The tie fraction is itself estimated over a shorter run of splits than Table S3 uses, which the table's note now says."));
else add(P("6. The comparator set excludes the rule's own subset and all comparisons are strict, so an exact tie counts against the rule. New Supplementary Table S1d reports how often ties occur."));
add(P("7. Thank you for the render check; the remaining whitespace follows from keeping full-page figures on their own pages."));

add(H1("Changes we made without being asked"));
add(P("Re-reading the paper against this review turned up several things wrong on their own terms. We list them so a reviewer does not have to find them next time."));
add(P("The cluster-bootstrap difference between currencies had been reported as the bootstrap mean rather than the observed difference; because the quartile edges are recut in each replicate, the two disagree in sign. The point estimates are now the observed differences and the gap is stated in Table S2c."));
add(P("Two sentences claimed more than their numbers showed. “Spreading the enrichment never hurts” is not what Table S4 shows: the effect is established at 6000 fitting patients and the point estimates run the other way at 600. “The effective-sample-size fraction is flat in the number of criteria” is not right either: it declines, from " + (OVC ? f(OVC[0].ess_frac,3) + " to " + f(OVC[OVC.length-1].ess_frac,3) : "\u2014") + " in colon, though not at every step and not at all over the first few Rotterdam steps. The size of the movement was always the point. The point of that table was always the size of the decline, and it now says that."));
add(P("Table S3 gave four matching tolerances on the hazard ratio but only one on the restricted mean, while the text claimed both estimands at all four; the three rows are added, as is the published rule's probability of a greater restricted mean difference with its interval, which had appeared in Table 1 without one. Table 1's caption also claimed the primary script supplies every point estimate in the paper, which Text S1.6 had been corrected to deny; it now points at that scoped list."));
add(P("Three smaller ones. The Methods said six interval procedures and the Results four; counting the unusable model-based intervals in Table S2b it is seven, and the Methods now says which two use a standard-deviation multiplier. The eligibility promise was described as rising from the smallest fitting size, but the curve is not monotone. And the claim that adjusted confounding costs “roughly twice the sample” holds at one reliability target, not at the one the same sentence quotes; the target is now named."));

add(new Paragraph({spacing:{before:300},children:[new TextRun({
  text:"The pattern in comment 1 is one we should learn from rather than only fix: we found the symptom, wrote it down, and did not follow it to the conclusion that the interval was the wrong object. Reporting an anomaly is not the same as acting on it.",
  size:21,font:"Calibri",italics:true})]}));

const doc=new Document({sections:[{properties:{page:{size:{width:12240,height:15840},
  margin:{top:1000,bottom:960,left:1120,right:1120}}},children:body}]});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync("response_to_reviewer_round7.docx",b);
  console.log("written",b.length,"bytes");});
