module.exports = function (M) {
const {add, P, H1, H2, R, table, FIG, NUM, f, f0, pct, CITE} = M;
const FA = NUM.factorial || {}, RB = NUM.random || {}, DP = NUM.dependence || {},
      RC = NUM.recovery || null, LF = NUM.leverage_forms, BY = (NUM.factorial||{}).by || {};
const PA = NUM.pareto || {}, CN = NUM.concentration || {}, RCI = NUM.random_ci || {};
const has = x => x !== undefined && x !== null;

add(H1("Results"));

/* ---------- 1 ---------- */
add(H2("The two promises are different kinds of claim"));
add(P("The eligible count behaved as the monotonicity argument requires: across 500 colon splits the minimum difference was exactly zero, never negative. The rule removed at least one criterion in 99.0% of splits, and in a further 1.2% the removals did not bind on the scoring half. The probability that more patients are admitted, 0.978, is the difference between those two — so it describes how often the rule removes a binding criterion, rather than whether the criteria it removed were the right ones."));
if (has(PA.colon)) {
  add(P("Whether the rule is doing more than removing criteria needs a comparison at the same level of inclusiveness, which our first attempt did not provide: it matched random relaxations on the number of criteria removed, and since the rule admitted 442 patients against random relaxation's 664 in Rotterdam, the hazard ratios were being compared at different eligible counts. We therefore score every one of the 512 subsets on the held-out half and place the rule among them."));
  add(P("Matched on eligible count to within ten per cent — a median of " + f0(PA.colon.n_match) + " comparators per split in colon and " + f0(PA.rott.n_match) + " in Rotterdam — the rule achieves a lower log hazard ratio than a matched subset in " + pct(PA.colon.rank_hr[0]) + " of comparisons in colon (95% interval " + pct(PA.colon.rank_hr[1]) + " to " + pct(PA.colon.rank_hr[2]) + ") and " + pct(PA.rott.rank_hr[0]) + " in Rotterdam (" + pct(PA.rott.rank_hr[1]) + " to " + pct(PA.rott.rank_hr[2]) + "). On the restricted mean difference it is at or below chance: " + pct(PA.colon.rank_rm[0]) + " and " + pct(PA.rott.rank_rm[0]) + ". So at equal inclusiveness the advantage is real on the hazard ratio but small, and absent on the absolute-benefit estimand."));
  add(P("The frontier comparison is less kind. A subset dominates the rule's choice if it admits at least as many patients at a hazard ratio at least as low. The rule's choice was on that frontier in " + pct(PA.colon.front_hr[0]) + " of colon splits and " + pct(PA.rott.front_hr[0]) + " of Rotterdam splits, with a median of " + f0(PA.colon.n_dom) + " and " + f0(PA.rott.n_dom) + " subsets dominating it. Whatever the Shapley rule optimises, it is not the eligible-count-versus-hazard-ratio trade-off, and out of sample it is usually some distance from the attainable frontier in both."));
  add(P("The earlier same-size comparison, retained for completeness with intervals across splits: the rule beat a random relaxation removing the same number of criteria on the hazard ratio in " + pct(RCI.colon.hr[0]) + " (" + pct(RCI.colon.hr[1]) + " to " + pct(RCI.colon.hr[2]) + ") of colon comparisons and " + pct(RCI.rott.hr[0]) + " (" + pct(RCI.rott.hr[1]) + " to " + pct(RCI.rott.hr[2]) + ") in Rotterdam, and on eligible count in " + pct(RCI.colon.cnt[0]) + " and " + pct(RCI.rott.cnt[0]) + ". These intervals are computed across splits and are therefore narrower than the population uncertainty of the next section."));
}
add(P("The effect-estimate promise was not kept in either cohort. In colon the out-of-sample hazard ratio was 0.078 higher under the data-driven protocol, lower in only 27.0% of splits; in Rotterdam the difference was 0.001 and the probability 0.497. Raising the fitting fraction to 0.7 moved these to 0.336 and 0.527, in the expected direction but not far enough. The absolute-benefit column moved consistently in neither."));
add(table(
  ["Out-of-sample comparison", "colon (n = 619)", "Rotterdam (n = 2982)"],
  [["Fitting set (fraction 0.5); splits", "309;  500", "1491;  400"],
   ["Original protocol, out of sample", "n = 88, HR = 0.592, RMST = +75.8 days", "n = 210, HR = 0.740, RMST = +143.9 days"],
   ["Data-driven protocol, out of sample", "n = 148, HR = 0.670, RMST = +70.0 days", "n = 440, HR = 0.742, RMST = +150.8 days"],
   ["Eligible patients: difference", "+59 (SE 2)", "+229 (SE 6)"],
   ["Hazard ratio: difference; P(lower)", "+0.0781; 0.270", "+0.0012; 0.497"],
   ["RMST: difference; P(greater)", "−5.8 d; 0.452", "+6.9 d; 0.580"]],
  [3100, 3130, 3130],
  "Table 1. Out-of-sample comparison against the original full protocol. The eligible-count row is monotone by construction and is reported for completeness rather than as a test. Rotterdam hazard ratios are descriptive: that cohort shows a severe lack of empirical overlap inside the full protocol."));

/* ---------- 2 ---------- */
add(H2("Repeated splits are not independent replicates"));
if (has(DP.colon)) {
  add(P("Resampling the cohort around the whole split procedure separates algorithmic stability from population uncertainty. Because a bootstrap resample contains duplicate copies of a patient, the inner split is taken over unique patient identifiers so that no patient contributes to both halves; an earlier version of this analysis split the resampled rows directly, which allowed copies of one patient to fall on opposite sides, and the numbers below are the corrected ones. Correcting it narrowed rather than widened the intervals."));
  add(P("With " + DP.colon.B + " outer resamples and " + DP.colon.R_IN + " inner splits each, the standard deviation of the colon probability of a lower out-of-sample hazard ratio across resamples is " + f(DP.colon.se_lower,3) + ". Of that, " + f(DP.colon.mc_lower,3) + " is the inner Monte Carlo component implied by " + DP.colon.R_IN + " splits and " + f(DP.colon.between_lower,3) + " is the between-cohort component obtained by subtracting it. The naive across-split standard error is " + f(DP.colon.naive_lower,4) + ", so the between-cohort component alone is " + f(DP.colon.ratio_between_lower,0) + " times it. The 95% percentile interval runs from " + f(DP.colon.ci_lower[0],2) + " to " + f(DP.colon.ci_lower[1],2) + "; in Rotterdam, from " + f(DP.rott.ci_lower[0],2) + " to " + f(DP.rott.ci_lower[1],2) + ". We use percentile rather than accelerated intervals because the statistic is a proportion of proportions and the acceleration estimate is unstable at this outer count."));
  add(P("These intervals cover most of the range: the point estimates of 0.270 and 0.497 are properties of these datasets rather than estimates of how often the procedure would succeed elsewhere, and an in-sample evaluation on a single cohort has access to neither source of variability. The eligibility probability is better determined, interval [" + f(DP.colon.ci_more[0],2) + ", " + f(DP.colon.ci_more[1],2) + "] in colon, as one expects of a quantity that is monotone by construction."));
}

/* ---------- 3 ---------- */
add(H2("No universal data requirement can be stated, and the reason is not sample size"));
add(P("With the scoring set fixed at 100 000 patients, the eligibility promise was kept at every fitting size, from 0.950 at 300 patients to 1.000 at 20 000. The effect-estimate promise rose from 0.273 to 0.997 over the same range, crossing 0.8 near 3000 and reaching 0.937 at 5167. At the population level the rule was correct: it identified the diluting criterion and its protocol lowered the hazard ratio from 0.6637 to 0.6327 while raising the eligible count from 55 179 to 78 847. The observed colon values sit close to this curve — 0.270 against a predicted 0.279 at 309 fitting patients, and 0.336 against 0.339 at 433 — but the interval around those observed values, from the previous section, spans most of the unit interval, so the agreement has almost no power to discriminate and we draw no validation from it."));
if (has(FA.n_med)) {
  const FX = NUM.fixedn ? NUM.fixedn.cells : null;
  add(P("That curve belongs to one generating mechanism. Across the resolution-IV factorial the threshold does not transfer: in " + FA.n_right + " of 16 scenarios the crossing was above the largest fitting size we evaluated, 18 000, and in one it was below the smallest. Estimating a threshold and then summarising only the scenarios where one was observable conditions on the outcome, so we report instead the success probability at fixed fitting sizes, which every scenario supplies whether or not it has an attainable threshold."));
  if (FX) {
    add(table(
      ["Fitting patients", "Effect modification concentrated: median [min, max]", "Spread over five criteria: median [min, max]"],
      [["600",   f(FX.n600.conc_med,2)   + " [" + f(FX.n600.conc_lo,2)   + ", " + f(FX.n600.conc_hi,2)   + "]", f(FX.n600.diff_med,2)   + " [" + f(FX.n600.diff_lo,2)   + ", " + f(FX.n600.diff_hi,2)   + "]"],
       ["2 000", f(FX.n2000.conc_med,2)  + " [" + f(FX.n2000.conc_lo,2)  + ", " + f(FX.n2000.conc_hi,2)  + "]", f(FX.n2000.diff_med,2)  + " [" + f(FX.n2000.diff_lo,2)  + ", " + f(FX.n2000.diff_hi,2)  + "]"],
       ["6 000", f(FX.n6000.conc_med,2)  + " [" + f(FX.n6000.conc_lo,2)  + ", " + f(FX.n6000.conc_hi,2)  + "]", f(FX.n6000.diff_med,2)  + " [" + f(FX.n6000.diff_lo,2)  + ", " + f(FX.n6000.diff_hi,2)  + "]"],
       ["18 000",f(FX.n18000.conc_med,2) + " [" + f(FX.n18000.conc_lo,2) + ", " + f(FX.n18000.conc_hi,2) + "]", f(FX.n18000.diff_med,2) + " [" + f(FX.n18000.diff_lo,2) + ", " + f(FX.n18000.diff_hi,2) + "]"]],
      [2600, 3400, 3360],
      "Table 2. Probability of a lower out-of-sample hazard ratio at fixed fitting-cohort size, across all sixteen factorial scenarios, eight per column. Monte Carlo standard error is at most 0.071. No threshold is estimated, so nothing is censored and no scenario is excluded."));
  }
  add(P("The spread across scenarios at any fixed size is very large: the standard deviation of the success probability is " + f(NUM.fixedn.cells.n2000.sd_all,2) + " at 2000 fitting patients and " + f(NUM.fixedn.cells.n6000.sd_all,2) + " at 6000, on a scale bounded by one. An interval-censored regression using the censored runs as the interval information they are does not resolve it, because the arrangement factor completely separates the design and its coefficient is unbounded; it is in the supplement as supporting material only (Table S2b)."));
  add(P("We withdraw a claim made in the first revision, that the threshold is more variable in events and effective sample size than in patients: that was computed over the six scenarios in which a threshold was observable, a selected subset. Binning all sixteen by each currency instead, the three are indistinguishable — " + f(NUM.fixedn.spread_patients,2) + ", " + f(NUM.fixedn.spread_events,2) + " and " + f(NUM.fixedn.spread_ess,2) + ". None is more portable, and none determines the answer."));
  add(P("The 0.80 reliability target is a convention borrowed from power calculations and nothing depends on it: at 0.70 and 0.90 the median located threshold is 2000 and 4811 fitting patients and the separation between the two arrangements is unchanged (Table S2b)."));
}
add(P("The factorial contrasted modification concentrated in one criterion with modification spread over five, and describing the result as being about concentration turned out to be wrong. In that design the per-criterion coefficient was simply divided, so the diffuse arm also had a weaker DILUTING coefficient — 0.128 against 0.32 — and dilution is what the rule must detect, since relaxation can lower the hazard ratio only by dropping a criterion that selects patients who benefit less. Concentration and detection strength were confounded."));
if (CN && CN.A_dil1_enr1) {
  const g = k => CN[k].rows.map(r => f(r.p_lower,2)).join(" / ");
  add(P("A separate sweep separates them, holding the total modification fixed at 0.85 and varying only its arrangement. Spreading the ENRICHMENT does not matter: with the diluting coefficient fixed at 0.30, success at 600, 2000, 6000 and 18 000 fitting patients runs " + g("A_dil1_enr1") + " with enrichment in one criterion, " + g("B_dil1_enr2") + " split over two, and " + g("C_dil1_enr4") + " split over four. Splitting the DILUTION is what costs: with the same total but the diluting signal halved across two criteria, the same four sizes give " + g("D_dil2_enr1") + "."));
  add(P("So the quantity that governs the data requirement is not how concentrated the effect modification is but how large the single largest diluting coefficient is. That is a sharper statement and a less comfortable one, because it is precisely the quantity the analysis exists to discover. Positivity, logical implication and interaction leverage can all be computed before any outcome is examined; the magnitude of the strongest diluting effect-modification coefficient cannot. The data requirement therefore depends on an unknown of exactly the kind the procedure is meant to estimate, and no rule expressed in patients, events or effective sample size can substitute for it. We regard that as the main methodological result of this work, and it is a negative one."));
}
add(FIG("fig_trainsize.png", 618, 260,
  "Figure 3. Left: probability that each promise is kept by fitting-cohort size in the single-mechanism simulation, scoring set fixed at 100 000, with Monte Carlo intervals. The observed cohort points carry the outer-bootstrap intervals from the nested resampling, which span most of the unit interval; their apparent agreement with the simulated curve has little discriminating power and we draw no validation from it. Right: the probability that the rule recovers the exactly correct criterion set."));

/* ---------- 4 ---------- */
add(H2("Below the threshold the selected protocol can be slightly worse than the original"));
if (RC && RC.length) {
  const A0 = RC[0], AZ = RC[RC.length-1];
  add(P("Exact recovery of the criterion set rose from " + f(A0.exact) + " at " + f0(A0.n) + " fitting patients to " + f(AZ.exact) + " at " + f0(AZ.n) + ", but that is an unnecessarily strict standard when several protocols perform almost identically. The softer measures move monotonically: Hamming distance fell from " + f(A0.hamming,2) + " criteria to " + f(AZ.hamming,2) + ", Jaccard similarity rose from " + f(A0.jaccard) + " to " + f(AZ.jaccard) + ", false retention fell from " + f(A0.false_retain) + " to " + f(AZ.false_retain) + " and false relaxation from " + f(A0.false_relax) + " to " + f(AZ.false_relax) + ". Over-relaxation is the error that persists."));
  add(P("Regret needs defining before it is read. Ours is on the log hazard-ratio scale: the difference between the population log hazard ratio under the selected protocol and under the subset that minimises it, both evaluated on the fixed 100 000-patient scoring set. It is a single-objective measure that ignores eligible count, safety and every other clinical consideration, and because different protocols target different populations a larger regret means further from the lowest attainable hazard ratio rather than worse for a patient. The full protocol has a regret of its own, which is what makes the two comparable. In this generating model the rule's population limit set coincides with the minimising subset, so its asymptotic regret is zero; the Shapley-sign rule carries no general guarantee of reaching the global optimum when interactions are present and we claim this for this scenario only. Regret falls from " + f(A0.regret,4) + " at " + f0(A0.n) + " fitting patients to " + f(AZ.regret,4) + " at " + f0(AZ.n) + ". The full protocol's regret is " + f(NUM.recovery_full_regret,4) + ". The two cross near a thousand fitting patients: below that, the protocol the rule produces sits slightly further from the lowest attainable hazard ratio than the full protocol does. Read narrowly — as a statement about this one generating model and this one objective — it means the expected outcome for a small cohort is not a smaller improvement but a marginally worse position on that objective, applied to a larger group of patients. It is not a claim that the resulting protocol is clinically worse, which would need the other objectives weighed alongside it."));
}

/* ---------- 5 ---------- */
add(H2("Confounding moves the threshold, and unmeasured confounding hides itself"));
add(P("Correctly adjusted confounding lowered the curve throughout: at 5167 fitting patients the probability fell from 0.937 to 0.808, so roughly twice the sample is needed for a given reliability."));
add(P("The third arm is the more consequential result and requires care with language. Because all three arms share one outcome model, the true causal contrast is identical in all three by construction; what differs is the population limit of the weighted estimator under each adjustment. Omitting one confounder returned the reliability curve to randomised levels — 0.936 at 5167 against 0.937 — which might easily be read as reassurance. The estimator's population limit for the gap between protocols rose to 0.0408 from 0.0310, 32% larger, with the whole hazard ratio displaced from 0.664 to 0.757. Meanwhile the probability of recovering the correct criterion set fell from 0.280 to 0.116. The procedure appeared equally reliable while its selection was in fact less accurate, because the quantity it was detecting had itself been inflated by bias."));
add(P([R("Observing that the method performs well on real-world data therefore does not by itself indicate that adjustment was adequate. A useful sensitivity analysis compares the estimated gap under richer and poorer adjustment and expects it to shrink as adjustment improves — but that expectation holds only when the added variables are plausibly confounders. Adding an instrument can amplify residual bias"), CITE("myers2011"), R(" and adding a collider or mediator can create it, so the direction of travel is a warning worth heeding among substantively defensible adjustment sets, not a test that settles the question.")]));
add(FIG("fig_confound.png", 618, 250,
  "Figure 4. Three treatment-assignment mechanisms sharing one outcome model, with Monte Carlo intervals. Left: correctly adjusted confounding lowers the curve; omitting one confounder returns it to randomised levels. Centre: the population limit of the estimated gap is 32% larger under unmeasured confounding — the true causal gap is identical in all three arms. Right: correct selection meanwhile falls by more than half."));

/* ---------- 6 ---------- */
add(H2("Why the hazard ratio is the fragile leg"));
add(P("Under proportional hazards with the conditional hazard ratio fixed at 0.6 in every stratum, a criterion defined on the prognostic covariate changes no individual's relative benefit, yet its Shapley value on the log hazard ratio grew monotonically with prognostic strength, from −0.0008 with no heterogeneity to −0.066 at the strongest setting, while the marginal hazard ratio drifted from 0.599 to 0.804. The value at zero heterogeneity is the falsification point and the artefact vanished there. The restricted mean difference also moved, and in the opposite direction: it fell from 0.664 in the whole cohort to 0.599 in the selected group at the weakest setting and from 0.425 to 0.322 at the strongest, so its Shapley value is negative throughout. That is the expected direction and it corresponds to a real fact — a lower-risk group has less absolute survival to gain, because more of it survives the horizon regardless of treatment. The hazard-ratio movement corresponds to no fact of either kind, which is the concrete reason a lower hazard ratio must not be read as a better estimate."));
add(FIG("fig_sim.png", 618, 250,
  "Figure 5. Non-collapsibility as a dose–response. The conditional hazard ratio is 0.6 in every stratum at every point on these curves, so the criterion changes no individual's relative benefit; the Shapley value on the log hazard ratio nonetheless grows with prognostic strength and vanishes where there is no heterogeneity to collapse over."));

/* ---------- 7 ---------- */
add(H2("Pairwise interactions here are attenuated, not absent"));
add(P([R("The plate plot, adapted here from network meta-analysis"), CITE("ren2026"), R(", displays both estimands in one panel (Figure 6). Leverage is signed: positive correlation raises the joint eligibility rate above the product of the marginals, and once it rises far enough the factor can become negative, meaning the contrast flips sign rather than vanishing. Magnitude therefore measures attenuation. In colon the median magnitude was 0.013 and the maximum 0.086, with no pair of 36 above 0.10 and 35 of 36 below 0.05; in Rotterdam the median was 0.022, four pairs exceeded 0.10 and 26 of 36 fell below 0.05.")]));
add(P("The consequence is a power statement, not a structural one. A global permutation test on the colon interaction matrix returned p = 0.26 on the hazard ratio and 0.21 on the restricted mean, and no main effect survived multiplicity adjustment on either estimand. Because the contrast in these cells is attenuated by a factor of order 0.01 to 0.09, those nulls carry little information about effect modification: they bound what could have been detected at this attenuation and sample size and nothing more. The one class of cells about which a null is definitive is the logically implied pair, where the contrast is exactly zero and which the implication detector removes before testing."));
if (NUM.coverage) {
  const C = NUM.coverage;
  add(P("Against known truth over " + C.reps + " replicates at n = 1500, the bias-corrected and accelerated interval attained " + f(C.bca_null,3) + " coverage (Monte Carlo SE " + f(C.se_null,3) + ") for a null interaction, against a nominal 0.95, while the percentile interval over-covered at " + f(C.pct_null,3) + ". Since most cells of a real interaction matrix are null and their false-positive behaviour determines what gets reported, that is the comparison that matters. For a genuinely non-null interaction both under-covered, at " + f(C.bca_planted,3) + " and " + f(C.pct_planted,3) + " (Monte Carlo SE " + f(C.se_planted,3) + "). We recommend at least 1000 bootstrap replicates and 50 jackknife groups, and treating intervals for large interactions as mildly anticonservative."));
} else {
  add(P("[Coverage results pending.]"));
}
add(FIG("fig2_plate3.png", 400, 475,
  "Figure 6. The criteria plate plot for colon. Upper triangle, pairwise interaction on the log hazard ratio; lower triangle, on the restricted mean difference; diagonal, per-criterion main effects on both estimands, shaded by the fraction of the cohort the criterion excludes. Light hatching marks cells whose leverage is below 0.05 in magnitude — 35 of 36 here — and dense hatching cells that are arithmetic identities. A full-page version is Supplementary Figure S2."));

/* ================= DISCUSSION ================= */
add(H1("Discussion"));
add(P("Data-driven relaxation admits more patients, and it is worth being precise about what that shows. The rule retains a subset of the criteria, so the eligible set can only grow, and the probability reported for this promise measures how often a binding criterion is removed. Scored against all 512 subsets on the held-out half, the rule's choice lay on the eligible-count-versus-hazard-ratio frontier in 1.6% of colon splits and 3.0% of Rotterdam splits, with a median of 72 and 60 subsets admitting at least as many patients at a hazard ratio at least as low. Matched on eligible count its hazard-ratio advantage is real but modest, and on the absolute-benefit estimand it is at or below chance. The rule is therefore not optimising the trade-off between the two promises, and a comparison against the full protocol alone cannot show this."));
add(P("What a wider eligible population is worth clinically is a separate question no outcome model answers, and criteria are not all of a kind: those encoding safety, tolerability, feasibility or pharmacology should be designated non-relaxable before the procedure runs rather than left to a hazard ratio to adjudicate."));
add(P("Whether the effect-estimate improvement is attainable at all depends on something that cannot be checked in advance. Across the factorial the success probability varies by roughly 0.34 in standard deviation at every fixed sample size, and grouping scenarios by events or by effective sample size rather than by patients does not reduce that spread at all — a claim we made in the previous revision and withdraw here, because it was computed only over the scenarios in which a threshold happened to be observable. The quantity that does govern the requirement is the magnitude of the largest diluting effect-modification coefficient: arranging the same total modification differently leaves success unchanged when the enrichment is spread and collapses it when the diluting signal is halved. Since that coefficient is what the analysis exists to estimate, no data requirement in patients, events or effective sample size can be given ahead of the analysis. We think this negative result is the more useful contribution, and it separates cleanly what an investigator can check beforehand — positivity inside the full protocol, logical implication, interaction leverage — from what they cannot."));
add(P("The regret comparison adds a further consideration for small cohorts, where the protocol the rule produces sits slightly further from the lowest attainable hazard ratio than the original full protocol does. That is a single-objective statement about one generating model and not a claim of clinical inferiority, but it does mean the caution for an investigator with a small cohort is not only that the expected improvement may fail to materialise."));
add(P("The unmeasured-confounding arm is the finding we would most want carried forward. Residual confounding inflated the quantity being detected and thereby made the procedure appear more reliable while its selection became less accurate, which runs against the usual intuition that a clear signal is reassuring. The recommendation that follows — compare adjustment sets and expect the gap to shrink — is a heuristic with real exceptions and should be used among substantively defensible sets rather than as a test."));
add(P("Rotterdam is a cautionary example of a different kind. Chemotherapy there went almost exclusively to younger, premenopausal women, so within the restrictive full protocol there is very little overlap and no specification we tried restores balance — exactly the check we argue should come first. Restriction does not create it; overlap was flat in the number of criteria applied in both cohorts."));
add(P("Three by-products may be useful independently. Interaction leverage is a closed-form quantity requiring no outcome data that says how far a pair's interaction is attenuated by the eligibility rates alone; we have corrected the claim made for it — low leverage is attenuation rather than structural invisibility — and derived the coefficient for three interaction forms, all multiples of (1−q)(1−q) under independence, exact for the both-criteria structure and approximate for the other two. The implication detector removes cells that are arithmetic identities, the only cells genuinely uninformative regardless of sample size. And carrying both estimands makes visible where a criterion's relative and absolute effects disagree, a substantive question that should be settled on clinical grounds rather than by a software default."));
add(P("Several limitations bound these conclusions. The criteria were constructed from available covariates rather than transcribed from protocols, so this demonstrates a general property rather than evaluating any trial, and neither cohort is the database used in the original work. The factorial is resolution IV, so two-factor interactions are aliased in pairs; the criterion-count factor spans only 6 against 8, because exhaustive enumeration costs 2^p evaluations per replicate; and propensity overlap, weight variability, missingness and model misspecification are represented crudely or not at all. All simulated quantities depend on their generating models. The absolute-benefit column depends on an analyst choice of horizon, and in colon its sign flips across a plausible range of that choice. The leverage expressions are derived for three specific interaction forms."));

add(H1("Conclusions"));
add(P("Relaxing trial eligibility criteria from data widens the eligible population, but that widening follows largely from the structure of the rule, and scored against the subsets attainable on held-out patients the rule's choice is rarely near the eligible-count-versus-hazard-ratio frontier. Its contribution is to the effect estimate, and it is modest at matched inclusiveness. How much data that contribution requires cannot be stated in advance: it is governed by the magnitude of the strongest diluting effect-modification coefficient, which is the quantity the analysis exists to discover, and no expression in patients, events or effective sample size stands in for it. Incomplete confounding adjustment can make the procedure appear more successful while its selection is less accurate, so apparent success on real-world data should not be taken as evidence of adequate adjustment. What an investigator can establish beforehand is narrower than we previously suggested — empirical overlap inside the full protocol, logical implication among criteria, and interaction leverage — and it does not include whether the effect-estimate promise is within reach."));
};
