module.exports = function (M) {
const {add, P, H1, H2, R, table, FIG, NUM, f, f0, pct, CITE} = M;
const FA = NUM.factorial || {}, RB = NUM.random || {}, DP = NUM.dependence || {},
      RC = NUM.recovery || null, LF = NUM.leverage_forms, BY = (NUM.factorial||{}).by || {};
const PA = NUM.pareto || {}, CN = NUM.concentration || {}, RCI = NUM.random_ci || {};
const NS = NUM.nested || {}, FO = NUM.frontier_opt || null, RR = NUM.rmst_rule || null;
const has = x => x !== undefined && x !== null;

add(H1("Results"));

/* ---------- 1 ---------- */
add(H2("The two promises are different kinds of claim"));
add(P("The eligible count behaved as the monotonicity argument requires: across 500 colon splits the minimum difference was exactly zero, never negative. The rule removed at least one criterion in 99.0% of splits and in a further 1.2% the removals did not bind on the scoring half, so the reported 0.978 describes how often a binding criterion is removed rather than whether the right ones were."));
if (NS.colon && NS.rott) {
  const C = NS.colon, RT = NS.rott;
  add(P("Whether the rule does more than remove criteria needs a comparison at equal inclusiveness, which our first attempt did not provide: it matched random relaxations on the NUMBER of criteria removed, and since the rule admitted 442 patients against random relaxation's 664 in Rotterdam, the hazard ratios were compared at different eligible counts. We therefore score all 512 subsets on the held-out half of each split, compute the proportion within a split, average splits with equal weight, and take the interval from the same patient-level outer bootstrap used for the two promises."));
  add(P("Matched to within ten per cent on eligible count — a median of " + f0(C["nm0.1"]) + " comparators per split in colon and " + f0(RT["nm0.1"]) + " in Rotterdam, sitting symmetrically around the rule's own count (mean relative difference " + f(C["sk0.1"],3) + " and " + f(RT["sk0.1"],3) + ") — the rule reaches a lower log hazard ratio than a matched subset in " + pct(C["hr0.1"].point) + " of colon comparisons and " + pct(RT["hr0.1"].point) + " in Rotterdam. With patient-level uncertainty the intervals are " + pct(C["hr0.1"].ci[0]) + " to " + pct(C["hr0.1"].ci[1]) + " and " + pct(RT["hr0.1"].ci[0]) + " to " + pct(RT["hr0.1"].ci[1]) + ", both of which contain one half. The advantage we described as real in the previous version is not established by these cohorts. In colon the point estimate stays between " + pct(Math.min(C["hr0.02"].point,C["hr0.05"].point,C["hr0.1"].point,C["hr0.15"].point)) + " and " + pct(Math.max(C["hr0.02"].point,C["hr0.05"].point,C["hr0.1"].point,C["hr0.15"].point)) + " across every tolerance from 2 to 15 per cent, consistently above one half but not separably so; in Rotterdam, whose estimates are descriptive in any case, it sits on one half at " + pct(RT["hr0.1"].point) + ". The earlier figures of 59.8% and 54.8% came from an interval computed across splits that share patients, and were narrower than the design supports."));
  add(P("On the restricted mean difference the point estimates sit at or below one half — " + pct(C["rm0.1"].point) + " in colon and " + pct(RT["rm0.1"].point) + " in Rotterdam — with intervals " + pct(C["rm0.1"].ci[0]) + " to " + pct(C["rm0.1"].ci[1]) + " and " + pct(RT["rm0.1"].ci[0]) + " to " + pct(RT["rm0.1"].ci[1]) + ". So such advantage as the point estimates suggest is specific to the hazard ratio and does not appear on the absolute-benefit estimand. That asymmetry matters, because the same paper shows hazard-ratio movement need not correspond to any individual's benefit, and it is the reason we no longer describe the procedure's contribution as being to the effect estimate in general."));
  add(P("The frontier comparison must be read with more care than we gave it. A subset dominates the rule if it admits at least as many patients at a hazard ratio at least as low, judged on the held-out half; on the observed cohorts the rule's choice was on that frontier in " + pct(C.front_hr.point) + " of colon splits and " + pct(RT.front_hr.point) + " of Rotterdam splits, with a median of " + f0(C.n_dom) + " and " + f0(RT.n_dom) + " subsets dominating it, and the outer-bootstrap intervals reach only " + pct(C.front_hr.ci[1]) + " and " + pct(RT.front_hr.ci[1]) + ". But this is an EMPIRICAL held-out frontier, taken as the best of 512 noisy estimates, and it is optimistic: the rule never saw the scoring half, yet the frontier is an argmax over that same half."));
  if (FO) {
    add(P("Simulation sizes that optimism. With the population known, a held-out half the size of a colon scoring set shows a median of " + f0(FO.dom_emp) + " apparently dominating subsets where the population has " + f0(FO.dom_pop) + ", and puts the rule off the frontier in " + pct(1-FO.front_emp) + " of replicates against " + pct(1-FO.front_pop) + " at the population. Of the subsets dominating on one held-out half, " + pct(FO.repro) + " still dominate on an independent half and only " + pct(FO.true_frac) + " genuinely dominate at the population. These numbers should therefore be read as the rule's distance from an optimistic oracle rather than as a measure of algorithmic inefficiency: the ordering survives the correction — the rule is not close to the best attainable protocol — but the magnitude does not, and cohorts this size cannot pin it down."));
    
  }
}

add(P("The effect-estimate promise was not kept in either cohort. In colon the out-of-sample hazard ratio was 0.078 higher under the data-driven protocol, lower in only 27.0% of splits; in Rotterdam the difference was 0.001 and the probability 0.497. Raising the fitting fraction to 0.7 moved these to 0.336 and 0.527, in the expected direction but not far enough. The absolute-benefit column moved consistently in neither."));
add(table(
  ["Out-of-sample comparison", "colon (n = 619)", "Rotterdam (n = 2982)"],
  [["Fitting set (fraction 0.5); splits", "309;  500", "1491;  400"],
   ["Original protocol, out of sample", "n = 88, HR = 0.592, RMST = +75.8 days", "n = 210, HR = 0.740, RMST = +143.9 days"],
   ["Data-driven protocol, out of sample", "n = 148, HR = 0.670, RMST = +70.0 days", "n = 440, HR = 0.742, RMST = +150.8 days"],
   ["Eligible patients: difference", "+59 (SE 2)", "+229 (SE 6)"],
   ["Hazard ratio: difference; P(lower)", "+0.0781; 0.270", "+0.0012; 0.497"],
   ["RMST: difference; P(greater)", "−5.8 days; 0.452", "+6.9 days; 0.580"]],
  [3100, 3130, 3130],
  "Table 1. Out-of-sample comparison against the original full protocol. The eligible-count row is monotone by construction and is reported for completeness rather than as a test. Rotterdam hazard ratios are descriptive: that cohort shows a severe lack of empirical overlap inside the full protocol."));

/* ---------- 2 ---------- */
add(H2("Repeated splits are not independent replicates"));
if (has(DP.colon)) {
  add(P("Resampling the cohort around the whole split procedure separates algorithmic stability from population uncertainty. Because a bootstrap resample contains duplicate copies of a patient, the inner split is taken over unique patient identifiers so that no patient contributes to both halves; an earlier version of this analysis split the resampled rows directly, which allowed copies of one patient to fall on opposite sides, and the numbers below are the corrected ones. Correcting it narrowed rather than widened the intervals."));
  add(P("With " + DP.colon.B + " outer resamples and " + DP.colon.R_IN + " inner splits each, the standard deviation of the colon probability of a lower out-of-sample hazard ratio across resamples is " + f(DP.colon.se_lower,3) + ". Of that, " + f(DP.colon.mc_lower,3) + " is the inner Monte Carlo component implied by " + DP.colon.R_IN + " splits and " + f(DP.colon.between_lower,3) + " is the between-cohort component obtained by subtracting it. The naive across-split standard error is " + f(DP.colon.naive_lower,4) + ", so the between-cohort component alone is " + f(DP.colon.ratio_between_lower,0) + " times it. The 95% percentile interval runs from " + f(DP.colon.ci_lower[0],2) + " to " + f(DP.colon.ci_lower[1],2) + "; in Rotterdam, from " + f(DP.rott.ci_lower[0],2) + " to " + f(DP.rott.ci_lower[1],2) + ". We use percentile rather than accelerated intervals because the statistic is a proportion of proportions and the acceleration estimate is unstable at this outer count."));
  add(P("These intervals cover most of the range: the point estimates of 0.270 and 0.497 are properties of these datasets rather than estimates of how often the procedure would succeed elsewhere, and an in-sample evaluation on a single cohort has access to neither source of variability. The eligibility probability is better determined, interval [" + f(DP.colon.ci_more[0],2) + ", " + f(DP.colon.ci_more[1],2) + "] in colon, as one expects of a quantity that is monotone by construction."));
}

/* ---------- 3 ---------- */
add(H2("No unconditional data requirement exists, and the reason is not sample size"));
add(P("With the scoring set fixed at 100 000 patients, the eligibility promise was kept at every fitting size, from 0.950 at 300 patients to 1.000 at 20 000. The effect-estimate promise rose from 0.273 to 0.997 over the same range, crossing 0.8 near 3000 and reaching 0.937 at 5167. At the population level the rule was correct: it identified the diluting criterion and its protocol lowered the hazard ratio from 0.6637 to 0.6327 while raising the eligible count from 55 179 to 78 847. The observed colon values sit close to this curve — 0.270 against a predicted 0.279 at 309 fitting patients, and 0.336 against 0.339 at 433 — but the interval around those observed values, from the previous section, spans most of the unit interval, so the agreement has almost no power to discriminate and we draw no validation from it."));
if (has(FA.n_med)) {
  const FX = NUM.fixedn ? NUM.fixedn.cells : null;
  add(P("That curve belongs to one generating mechanism, and across the resolution-IV factorial the threshold does not transfer: in " + FA.n_right + " of 16 scenarios the crossing lay above the largest fitting size evaluated and in one below the smallest. We therefore report the success probability at fixed fitting sizes, which every scenario supplies."));
  if (FX) {
    add(table(
      ["Fitting patients", "Effect modification concentrated: median [min, max]", "Spread over five criteria: median [min, max]"],
      [["600",   f(FX.n600.conc_med,2)   + " [" + f(FX.n600.conc_lo,2)   + ", " + f(FX.n600.conc_hi,2)   + "]", f(FX.n600.diff_med,2)   + " [" + f(FX.n600.diff_lo,2)   + ", " + f(FX.n600.diff_hi,2)   + "]"],
       ["2 000", f(FX.n2000.conc_med,2)  + " [" + f(FX.n2000.conc_lo,2)  + ", " + f(FX.n2000.conc_hi,2)  + "]", f(FX.n2000.diff_med,2)  + " [" + f(FX.n2000.diff_lo,2)  + ", " + f(FX.n2000.diff_hi,2)  + "]"],
       ["6 000", f(FX.n6000.conc_med,2)  + " [" + f(FX.n6000.conc_lo,2)  + ", " + f(FX.n6000.conc_hi,2)  + "]", f(FX.n6000.diff_med,2)  + " [" + f(FX.n6000.diff_lo,2)  + ", " + f(FX.n6000.diff_hi,2)  + "]"],
       ["18 000",f(FX.n18000.conc_med,2) + " [" + f(FX.n18000.conc_lo,2) + ", " + f(FX.n18000.conc_hi,2) + "]", f(FX.n18000.diff_med,2) + " [" + f(FX.n18000.diff_lo,2) + ", " + f(FX.n18000.diff_hi,2) + "]"]],
      [2600, 3400, 3360],
      "Table 2. Probability of a lower out-of-sample hazard ratio at fixed fitting-cohort size, across all sixteen factorial scenarios, eight per column. Monte Carlo standard error is at most 0.071. No threshold is estimated, so nothing is censored and no scenario is excluded."));
  }
  add(P("The spread across scenarios at any fixed size is large — the standard deviation of the success probability is " + f(NUM.fixedn.cells.n2000.sd_all,2) + " at 2000 fitting patients and " + f(NUM.fixedn.cells.n6000.sd_all,2) + " at 6000, on a scale bounded by one — and an interval-censored regression cannot resolve it, because the arrangement factor completely separates the design (Table S2b)."));
  add(P("We withdraw a claim made in the first revision, that the threshold is more variable in events and effective sample size than in patients: that was computed over the six scenarios in which a threshold was observable, a selected subset. Binning all sixteen by each currency instead, the three are indistinguishable — " + f(NUM.fixedn.spread_patients,2) + ", " + f(NUM.fixedn.spread_events,2) + " and " + f(NUM.fixedn.spread_ess,2) + ". None is more portable, and none determines the answer."));
  add(P("The 0.80 reliability target is a convention borrowed from power calculations and nothing depends on it: at 0.70 and 0.90 the median located threshold is 2000 and 4811 fitting patients and the separation between the two arrangements is unchanged (Table S2b)."));
}
add(P("The factorial contrasted modification concentrated in one criterion with modification spread over five, and describing the result as being about concentration turned out to be wrong. In that design the per-criterion coefficient was simply divided, so the diffuse arm also had a weaker DILUTING coefficient — 0.128 against 0.32 — and dilution is what the rule must detect, since relaxation can lower the hazard ratio only by dropping a criterion that selects patients who benefit less. Concentration and detection strength were confounded."));
if (CN && CN.A_dil1_enr1) {
  const g = k => CN[k].rows.map(r => f(r.p_lower,2)).join(" / ");
  add(P("A separate sweep separates them, holding the total modification fixed at 0.85 and varying only its arrangement. With the diluting coefficient fixed at 0.30, success at 600, 2000, 6000 and 18 000 fitting patients runs " + g("A_dil1_enr1") + " with the enrichment in one criterion, " + g("B_dil1_enr2") + " split over two and " + g("C_dil1_enr4") + " split over four. Spreading the enrichment never hurts, and at 6000 patients it helps by 0.21 (95% interval 0.08 to 0.34) and 0.20 (0.07 to 0.33) — so it is not, as we first wrote, without effect. Splitting the DILUTION goes the other way at every size: the same total with the diluting signal halved across two criteria gives " + g("D_dil2_enr1") + ", differences from the first arrangement of −0.19, −0.26, −0.39 and −0.42, every interval excluding zero."));
  add(P("Two cautions belong with that comparison. The arrangements hold the full-protocol hazard ratio exactly equal, since under the full protocol the treated bonus is the sum of the coefficients, which the design fixes; they do not hold the ATTAINABLE improvement equal. On a 120 000-patient evaluation set the best subset reaches 0.6698 against a full-protocol 0.6900 in the three arrangements that concentrate the dilution, a gap of 0.0203, and 0.6803 in the one that splits it, a gap of 0.0098. Splitting the dilution halves the prize as well as the coefficient, and the two cannot be separated, because the attainable gap is itself determined by how the dilution is distributed. Arrangements that concentrate it present both a larger coefficient and a larger prize and are correspondingly easier; the sweep does not isolate the coefficient."));
add(P("The second is that a raw coefficient is unlikely to be the general governing quantity at all: the same coefficient on a criterion retaining 90% of a cohort and on one retaining 30% carries different information, and detectability must also depend on prevalence, correlation among criteria, retained events, censoring and weight variability. A criterion-specific signal-to-noise ratio — the population Shapley value of the diluting criterion over the standard deviation of its estimate — is the more plausible candidate, and one comparison is suggestive: the three arrangements that concentrate the dilution share an identical diluting coefficient of 0.30 and near-identical population Shapley values, so the coefficient cannot separate them at all, while their signal-to-noise ratios (1.39, 1.51, 1.73) do order their observed success (0.58, 0.79, 0.78). Four arrangements cannot establish anything, and we offer this as the direction a general answer would take rather than as one."));
add(P("What survives is the consequence for planning. Whatever the right summary turns out to be, it is a property of the effect modification present, which is the quantity the analysis exists to estimate. Positivity, logical implication and interaction leverage can all be computed before any outcome is examined; the strength of the diluting signal cannot. So a data requirement cannot be read off cohort size, event count or effective sample size alone. It can be stated conditionally, on an assumed minimum diluting signal, exactly as a conventional power calculation is stated on an assumed minimum clinically relevant effect — and Table 2 read as a family of conditional reliability curves is that statement. What does not exist is an unconditional threshold, and it was one of those that we offered in the previous version."));
}
add(FIG("fig_trainsize.png", 618, 260,
  "Figure 3. Left: probability that each promise is kept by fitting-cohort size in the single-mechanism simulation, scoring set fixed at 100 000, with Monte Carlo intervals. The observed cohort points carry the outer-bootstrap intervals from the nested resampling, which span most of the unit interval; their apparent agreement with the simulated curve has little discriminating power and we draw no validation from it. Right: the probability that the rule recovers the exactly correct criterion set."));

/* ---------- 4 ---------- */
add(H2("Below the threshold the selected protocol can be slightly worse than the original"));
if (RC && RC.length) {
  const A0 = RC[0], AZ = RC[RC.length-1];
  add(P("Exact recovery of the criterion set rose from " + f(A0.exact) + " at " + f0(A0.n) + " fitting patients to " + f(AZ.exact) + " at " + f0(AZ.n) + ", but that is an unnecessarily strict standard when several protocols perform almost identically. The softer measures move monotonically: Hamming distance fell from " + f(A0.hamming,2) + " criteria to " + f(AZ.hamming,2) + ", Jaccard similarity rose from " + f(A0.jaccard) + " to " + f(AZ.jaccard) + ", false retention fell from " + f(A0.false_retain) + " to " + f(AZ.false_retain) + " and false relaxation from " + f(A0.false_relax) + " to " + f(AZ.false_relax) + ". Over-relaxation is the error that persists."));
  add(P("Regret needs defining before it is read. Ours is on the log hazard-ratio scale: the difference between the population log hazard ratio under the selected protocol and under the subset that minimises it, both evaluated on the fixed 100 000-patient scoring set. It is a single-objective measure that ignores eligible count, safety and every other clinical consideration, and because different protocols target different populations a larger regret means further from the lowest attainable hazard ratio rather than worse for a patient. The full protocol has a regret of its own, which is what makes the two comparable. In this generating model the rule's population limit set coincides with the minimising subset, so its asymptotic regret is zero; the Shapley-sign rule carries no general guarantee of reaching the global optimum when interactions are present and we claim this for this scenario only. Regret falls from " + f(A0.regret,4) + " at " + f0(A0.n) + " fitting patients to " + f(AZ.regret,4) + " at " + f0(AZ.n) + ". The full protocol's regret is " + f(NUM.recovery_full_regret,4) + ". The two cross near a thousand fitting patients: below that, the protocol the rule produces sits slightly further from the lowest attainable hazard ratio than the full protocol does. Read narrowly — as a statement about this one generating model and this one objective — it means the expected outcome for a small cohort is not a smaller improvement but a marginally worse position on that objective, applied to a larger group of patients. It is not a claim that the resulting protocol is clinically worse, which would need the other objectives weighed alongside it."));
}

/* ---------- 5 ---------- */
add(H2("Confounding moves the threshold, and unmeasured confounding hides itself"));
add(P("Correctly adjusted confounding lowered the curve throughout: at 5167 fitting patients the probability fell from 0.937 to 0.808, so roughly twice the sample is needed for a given reliability."));
add(P("The third arm is the more consequential result and requires care with language. Because all three arms share one outcome model, the true causal contrast is identical in all three by construction; what differs is the population limit of the weighted estimator under each adjustment. Omitting one confounder returned the reliability curve to randomised levels — 0.936 at 5167 against 0.937 — which might easily be read as reassurance. The estimator's population limit for the gap between protocols rose to 0.0408 from 0.0310, 32% larger, with the whole hazard ratio displaced from 0.664 to 0.757. Meanwhile the probability of recovering the correct criterion set fell from 0.280 to 0.116. The procedure appeared equally reliable while its selection was in fact less accurate, because the quantity it was detecting had itself been inflated by bias."));
add(P([R("Observing that the method performs well on real-world data therefore does not by itself indicate that adjustment was adequate. A useful sensitivity analysis compares the estimated gap under richer and poorer adjustment and expects it to shrink as adjustment improves — but that expectation holds only when the added variables are plausibly confounders. Adding an instrument can amplify residual bias"), CITE("myers2011"), R(" and adding a collider or mediator can create it, so the direction of travel is a warning worth heeding among substantively defensible adjustment sets, not a test that settles the question.")]));
add(FIG("fig_confound.png", 618, 250,
  "Figure 4. Three treatment-assignment mechanisms sharing one outcome model, with Monte Carlo intervals. Left: correctly adjusted confounding lowers the curve; omitting one confounder returns it to randomised levels. Centre: the population limit of the estimated gap is 32% larger under unmeasured confounding — the true causal gap is identical in all three arms. Right: correct selection meanwhile falls by more than half."));

/* ---------- 6 ---------- */
add(H2("Why the hazard ratio is the fragile leg"));
add(P("Under proportional hazards with the conditional hazard ratio fixed at 0.6 in every stratum, a criterion defined on the prognostic covariate changes no individual's relative benefit, yet its Shapley value on the log hazard ratio grew monotonically with prognostic strength, from −0.0008 with no heterogeneity to −0.066 at the strongest setting, while the marginal hazard ratio drifted from 0.599 to 0.804. The value at zero heterogeneity is the falsification point and the artefact vanished there. The restricted mean difference also moved, and in the opposite direction: it fell from 0.664 in the whole cohort to 0.599 in the selected group at the weakest setting and from 0.425 to 0.322 at the strongest, so its Shapley value is negative throughout. That is the expected direction and it corresponds to a real fact — a lower-risk group has less absolute survival to gain, because more of it survives the horizon regardless of treatment. The hazard-ratio movement corresponds to no fact of either kind, which is the concrete reason a lower hazard ratio must not be read as a better estimate."));
add(FIG("fig_sim.png", 618, 250,
  "Figure 5. Non-collapsibility as a dose–response. The conditional hazard ratio is 0.6 in every stratum at every point on these curves, so the criterion changes no individual's relative benefit; the Shapley value on the log hazard ratio nonetheless grows with prognostic strength and vanishes where there is no heterogeneity to collapse over."));

/* ---------- 7 ---------- */
add(H2("Pairwise interactions here are attenuated, not absent"));
add(P([R("The plate plot, adapted here from network meta-analysis"), CITE("ren2026"), R(", displays both estimands in one panel (Figure 6). Leverage is signed: positive correlation raises the joint eligibility rate above the product of the marginals, and once it rises far enough the factor can become negative, meaning the contrast flips sign rather than vanishing. Magnitude therefore measures attenuation. In colon the median magnitude was 0.013 and the maximum 0.086, with no pair of 36 above 0.10 and 35 of 36 below 0.05; in Rotterdam the median was 0.022, four pairs exceeded 0.10 and 26 of 36 fell below 0.05.")]));
add(P("The consequence is a power statement, not a structural one. A global permutation test on the colon interaction matrix returned p = 0.26 on the hazard ratio and 0.21 on the restricted mean, and no main effect survived multiplicity adjustment on either estimand. Because the contrast in these cells is attenuated by a factor of order 0.01 to 0.09, those nulls carry little information about effect modification: they bound what could have been detected at this attenuation and sample size and nothing more. The one class of cells about which a null is definitive is the logically implied pair, where the contrast is exactly zero and which the implication detector removes before testing."));
if (NUM.coverage) {
  const C = NUM.coverage;
  add(P("Against known truth over " + C.reps + " replicates at n = 1500, the bias-corrected and accelerated interval attained " + f(C.bca_null,3) + " coverage (Monte Carlo SE " + f(C.se_null,3) + ") for a null interaction, against a nominal 0.95, while the percentile interval over-covered at " + f(C.pct_null,3) + ". Since most cells of a real interaction matrix are null and their false-positive behaviour determines what gets reported, that is the comparison that matters. For a genuinely non-null interaction both under-covered, at " + f(C.bca_planted,3) + " and " + f(C.pct_planted,3) + " (Monte Carlo SE " + f(C.se_planted,3) + "). We recommend at least 1000 bootstrap replicates and 50 jackknife groups, and treating intervals for large interactions as mildly anticonservative."));
} else {
  add(P("[Coverage results pending.]"));
}
if (RR) {
  add(P("Because the advantage such as it is appears only on the hazard ratio, we asked what happens if the rule selects on the restricted mean difference instead — retaining every criterion whose RMST Shapley value is positive. The two rules are almost different procedures: they agree on the criterion set in " + pct(RR.colon.same) + " of colon splits, and the RMST rule admits " + f0(RR.colon.n_rm) + " patients against the hazard-ratio rule's " + f0(RR.colon.n_hr) + " and the full protocol's " + f0(RR.colon.n_full) + ". Yet selecting on the absolute-benefit estimand does not deliver absolute benefit: out of sample the RMST rule exceeds the full protocol's restricted mean difference in " + pct(RR.colon.rm_moreRM) + " of colon splits against " + pct(RR.colon.hr_moreRM) + " for the hazard-ratio rule, and its mean out-of-sample difference is " + f(RR.colon.rmRM,1) + " days against the full protocol's " + f(RR.colon.fullRM,1) + ". On the hazard ratio it is worse than the rule it replaces (" + pct(RR.colon.rm_lowerHR) + " against " + pct(RR.colon.hr_lowerHR) + "). The choice of decomposition estimand therefore changes the selected criteria almost completely while improving neither estimand out of sample, so an investigator whose endpoint is absolute benefit gains nothing by switching the rule to it."));
  
}
add(FIG("fig2_plate3.png", 440, 522,
  "Figure 6. The criteria plate plot for colon. Upper triangle, pairwise interaction on the log hazard ratio; lower triangle, on the restricted mean difference; diagonal, per-criterion main effects on both estimands, shaded by the fraction of the cohort the criterion excludes. Light hatching marks cells whose leverage is below 0.05 in magnitude — 35 of 36 here — and dense hatching cells that are arithmetic identities. A full-page version is Supplementary Figure S2."));

/* ================= DISCUSSION ================= */
add(H1("Discussion"));
add(P("Data-driven relaxation admits more patients, and it is worth being precise about what that shows. The rule retains a subset of the criteria, so the eligible set can only grow, and the probability reported for this promise measures how often a binding criterion is removed. Scored against all 512 subsets on the held-out half, the rule's choice is almost never on the empirical eligible-count-versus-hazard-ratio frontier, though simulation shows that frontier is itself optimistic and the honest reading is a distance from an optimistic oracle rather than a measure of inefficiency. Matched on eligible count, its hazard-ratio advantage has an interval containing one half, and on the absolute-benefit estimand the point estimate sits below one half. So the rule is not optimising the trade-off between the two promises, and whether it has any advantage at equal inclusiveness is a question these cohorts cannot settle — neither of which a comparison against the full protocol alone can show."));
add(P("What a wider eligible population is worth clinically is a separate question no outcome model answers, and criteria are not all of a kind: those encoding safety, tolerability, feasibility or pharmacology should be designated non-relaxable before the procedure runs rather than left to a hazard ratio to adjudicate."));
add(P("Whether the effect-estimate improvement is attainable depends on something that cannot be checked before the analysis, but that does not make planning impossible. Across the factorial the success probability varies by roughly 0.34 in standard deviation at every fixed sample size, and grouping scenarios by events or by effective sample size rather than by patients does not reduce that spread at all — a claim we made in the previous revision and withdraw here, because it was computed only over the scenarios in which a threshold happened to be observable. The quantity that does govern the requirement is the magnitude of the largest diluting effect-modification coefficient: arranging the same total modification differently leaves success unchanged when the enrichment is spread and collapses it when the diluting signal is halved. Since the strength of the diluting signal is what the analysis exists to estimate, no data requirement in patients, events or effective sample size can be given unconditionally. That is the same situation as any power calculation, where the sample size depends on an effect size not yet observed, and the same remedy applies: state a minimum diluting signal one would not want to miss and read the requirement off conditional curves, which is how Table 2 should be used. What we can rule out is an unconditional threshold of the kind we ourselves offered in the previous version. The result also separates cleanly what an investigator can check beforehand — empirical overlap inside the full protocol, logical implication, interaction leverage — from what they cannot."));
add(P("For small cohorts the regret comparison adds a further caution: the protocol the rule produces sits slightly further from the lowest attainable hazard ratio than the original does. That is a single-objective statement about one generating model, not a claim of clinical inferiority."));
add(P("The unmeasured-confounding arm is the finding we would most want carried forward. Residual confounding inflated the quantity being detected and thereby made the procedure appear more reliable while its selection became less accurate, which runs against the usual intuition that a clear signal is reassuring. The recommendation that follows — compare adjustment sets and expect the gap to shrink — is a heuristic with real exceptions and should be used among substantively defensible sets rather than as a test."));
add(P("Rotterdam is a cautionary example of a different kind. Chemotherapy there went almost exclusively to younger, premenopausal women, so within the restrictive full protocol there is very little overlap and no specification we tried restores balance — exactly the check we argue should come first. Restriction does not create it; overlap was flat in the number of criteria applied in both cohorts."));
add(P("Three by-products may be useful independently. Interaction leverage is a closed-form quantity requiring no outcome data that says how far a pair's interaction is attenuated by the eligibility rates alone; we have corrected the claim made for it — low leverage is attenuation rather than structural invisibility — and derived the coefficient for three interaction forms, all multiples of (1−q)(1−q) under independence, exact for the both-criteria structure and approximate for the other two. The implication detector removes cells that are arithmetic identities, the only cells genuinely uninformative regardless of sample size. And carrying both estimands makes visible where a criterion's relative and absolute effects disagree, a substantive question that should be settled on clinical grounds rather than by a software default."));
add(P("Several limitations bound these conclusions. The criteria were constructed from available covariates rather than transcribed from protocols, so this demonstrates a general property rather than evaluating any trial, and neither cohort is the database used in the original work. The factorial is resolution IV, so two-factor interactions are aliased in pairs; the criterion-count factor spans only 6 against 8, because exhaustive enumeration costs 2^p evaluations per replicate; and propensity overlap, weight variability, missingness and model misspecification are represented crudely or not at all. All simulated quantities depend on their generating models. The absolute-benefit column depends on an analyst choice of horizon, and in colon its sign flips across a plausible range of that choice. The leverage expressions are derived for three specific interaction forms."));

add(H1("Conclusions"));
add(P("Relaxing trial eligibility criteria from data widens the eligible population, but that widening follows largely from the structure of the rule, and scored against the subsets attainable on held-out patients the rule's choice is rarely near the eligible-count-versus-hazard-ratio frontier. Whether it contributes anything at matched inclusiveness is not resolved by cohorts of this size; the point estimates favour it on the hazard ratio and not on absolute benefit, and a variant selecting on absolute benefit instead chooses almost entirely different criteria without improving either estimand. How much data that contribution requires cannot be read from patients, events or effective sample size alone: it depends on the strength of the diluting signal, which is the quantity the analysis exists to discover. It can be stated conditionally on an assumed minimum such signal, as a power calculation is stated on an assumed minimum effect; what does not exist is an unconditional threshold. Incomplete confounding adjustment can make the procedure appear more successful while its selection is less accurate, so apparent success on real-world data should not be taken as evidence of adequate adjustment. What an investigator can establish beforehand is narrower than we previously suggested — empirical overlap inside the full protocol, logical implication among criteria, and interaction leverage — and it does not include whether the effect-estimate promise is within reach."));
};
