module.exports = function (M) {
const {add, P, H1, H2, R, table, FIG, NUM, f, f0, pct, CITE} = M;
const FA = NUM.factorial || {}, RB = NUM.random || {}, DP = NUM.dependence || {},
      RC = NUM.recovery || null, LF = NUM.leverage_forms, BY = (NUM.factorial||{}).by || {};
const PA = NUM.pareto || {}, CN = NUM.concentration || {}, RCI = NUM.random_ci || {};
const NS = NUM.nested || {}, FO = NUM.frontier_opt || null, RR = NUM.rmst_rule || null;
const PR = NUM.primary || {};
const has = x => x !== undefined && x !== null;

add(H1("Results"));

/* ---------- 1 ---------- */
add(H2("The two promises are different kinds of claim"));
add(P("The eligible count behaved as the monotonicity argument requires: across 500 colon splits the minimum difference was exactly zero, never negative. The rule removed at least one criterion in 99.0% of splits and in a further 1.2% the removals did not bind on the scoring half, so the reported 0.978 describes how often a binding criterion is removed rather than whether the right ones were."));
if (PR.colon && NS.colon) {
  const C = PR.colon, R = PR.rott, NC = NS.colon, NR = NS.rott;
  const iv = (pt, sd) => "[" + f(Math.max(0, pt - 1.96*sd),2) + ", " + f(Math.min(1, pt + 1.96*sd),2) + "]";
  add(P("Whether the rule does more than remove criteria needs a comparison at equal inclusiveness, which our first attempt did not provide: it matched random relaxations on the NUMBER of criteria removed, not on how many patients they admitted. We therefore score all 512 subsets on the held-out half of each split, compute the proportion within a split, and average splits with equal weight. Point estimates come from the full " + C.R + " and " + R.R + " splits; the interval is the point estimate plus or minus twice the outer-sampling standard deviation from the nested bootstrap, which is the total across-resample spread with the inner Monte Carlo component removed."));
  add(P("Matched to within ten per cent on eligible count — a median of " + f0(C["nm0.1"]) + " comparators per split in colon and " + f0(R["nm0.1"]) + " in Rotterdam, sitting symmetrically around the rule's own count (mean relative difference " + f(C["sk0.1"],3) + " and " + f(R["sk0.1"],3) + ") — the rule reaches a lower log hazard ratio than a matched subset in " + pct(C["hr0.1"]) + " of colon comparisons, interval " + iv(C["hr0.1"], NC["hr0.1"].sd_outer) + ", and " + pct(R["hr0.1"]) + " in Rotterdam, interval " + iv(R["hr0.1"], NR["hr0.1"].sd_outer) + ". The estimates are stable across matching tolerances from 2 to 15 per cent, moving between " + pct(Math.min(C["hr0.02"],C["hr0.05"],C["hr0.1"],C["hr0.15"])) + " and " + pct(Math.max(C["hr0.02"],C["hr0.05"],C["hr0.1"],C["hr0.15"])) + " in colon."));
  add(P("On the restricted mean difference the two cohorts disagree. In colon the rule is below one half at every tolerance (" + pct(C["rm0.1"]) + " at ten per cent, interval " + iv(C["rm0.1"], NC["rm0.1"].sd_outer) + "); in Rotterdam it is above (" + pct(R["rm0.1"]) + ", interval " + iv(R["rm0.1"], NR["rm0.1"].sd_outer) + "). Every one of these intervals contains one half. Neither an advantage nor its absence is established at equal inclusiveness, on either estimand, in either cohort — and the disagreement between the two estimands in colon is itself worth noting, given that the paper shows hazard-ratio movement need not track absolute benefit."));
  add(P("The frontier comparison must be read with more care than we gave it. A subset dominates the rule if it admits at least as many patients at a log hazard ratio at least as low, judged on the held-out half; on that criterion the rule's choice was on the frontier in " + pct(C.front_hr) + " of colon splits and " + pct(R.front_hr) + " of Rotterdam splits, with a median of " + f0(C.n_dom) + " and " + f0(R.n_dom) + " subsets dominating. Requiring a margin of " + f(C.margin,2) + " on the log hazard ratio — roughly a five per cent relative change, chosen as a value below which a difference would not change a protocol decision — raises frontier membership to " + pct(C.front_hrM) + " and " + pct(R.front_hrM) + ". But this is an EMPIRICAL held-out frontier, taken as the best of 512 noisy estimates on the same data used to judge it, and it is optimistic."));
  if (FO) {
    add(P("Simulation sizes that optimism, at a bare inequality rather than with a margin. With the population known, a held-out half the size of a colon scoring set shows a median of " + f0(FO.dom_emp) + " apparently dominating subsets where the population has " + f0(FO.dom_pop) + ", and puts the rule off the frontier in " + pct(1-FO.front_emp) + " of replicates against " + pct(1-FO.front_pop) + " at the population. Of the subsets dominating on one held-out half, " + pct(FO.repro) + " still dominate on an independent half and only " + pct(FO.true_frac) + " genuinely dominate at the population. These numbers therefore measure the rule's distance from an optimistic oracle constructed on the same data, not from the true optimum; simulation shows the direction of the bias and its size in one generating mechanism, and does not convert the observed-cohort frontier into an unbiased one."));
  }
  if (NUM.threeway) {
    const TC = NUM.threeway.colon, TR = NUM.threeway.rott;
    add(P("The same question can be put to the cohorts themselves without a generating model, by splitting three ways: the rule is fitted on one third, the subsets that dominate it are identified on a second, and exactly those subsets are re-evaluated on a third that has been used for nothing. In colon a median of " + f0(TC.dom_sel) + " subsets dominate on the selection third, of which " + pct(TC.repro) + " still dominate on the untouched third; in Rotterdam the figures are " + f0(TR.dom_sel) + " and " + pct(TR.repro) + ". Requiring the " + f(PR.colon.margin,2) + " margin on the selection third leaves a median of " + f0(TC.dom_selM) + " and " + f0(TR.dom_selM) + " candidates and raises carry-over to " + pct(TC.reproM) + " and " + pct(TR.reproM) + ". The single lowest-hazard-ratio dominator carries over in " + pct(TC.best_holds) + " and " + pct(TR.best_holds) + " of splits. Frontier membership itself changes little: the rule is on the frontier in " + pct(TC.front_sel) + " of colon splits judged on the selection third and " + pct(TC.front_test) + " judged on the untouched third. The optimism is therefore large in the number of apparent dominators and in how many of them survive, and small in the headline membership figure; the rule remains off the frontier in the great majority of splits even when the comparator is chosen on data it is not judged on. What we can say from all of this is that the rule is not close to an empirical optimistic oracle, and that the gap does not close when the oracle is made honest at the cost of a smaller evaluation set. How far it sits from the true best attainable protocol, these cohorts cannot tell us."));
  }

add(table(
  ["Out-of-sample comparison", "colon (n = 619)", "Rotterdam (n = 2982)"],
  [["Endpoint; horizon; splits", C.time_var+", "+C.status_var+"; "+f0(C.tau)+" d; "+C.R,
                                 R.time_var+", "+R.status_var+"; "+f0(R.tau)+" d; "+R.R],
   ["Original protocol, out of sample", "n = "+f0(C.n_full)+", HR = "+f(C.hr_full,3)+", RMST = "+f(C.rm_full,1)+" days",
                                        "n = "+f0(R.n_full)+", HR = "+f(R.hr_full,3)+", RMST = "+f(R.rm_full,1)+" days"],
   ["Data-driven protocol, out of sample", "n = "+f0(C.n_rule)+", HR = "+f(C.hr_rule,3)+", RMST = "+f(C.rm_rule,1)+" days",
                                        "n = "+f0(R.n_rule)+", HR = "+f(R.hr_rule,3)+", RMST = "+f(R.rm_rule,1)+" days"],
   ["Eligible patients: difference; P(more)", "+"+f0(C.d_n)+"; "+f(C.more,3), "+"+f0(R.d_n)+"; "+f(R.more,3)],
   ["Hazard ratio: difference; P(lower)", (C.d_hr>0?"+":"")+f(C.d_hr,4)+"; "+f(C.lower,3), (R.d_hr>0?"+":"")+f(R.d_hr,4)+"; "+f(R.lower,3)],
   ["RMST: difference; P(greater)", (C.d_rm>0?"+":"")+f(C.d_rm,1)+" days; "+f(C.greater,3), (R.d_rm>0?"+":"")+f(R.d_rm,1)+" days; "+f(R.greater,3)]],
  [3100, 3130, 3130],
  "Table 1. Out-of-sample comparison against the original full protocol, from the single primary analysis that supplies every point estimate in this paper and its supplement; the nested bootstrap supplies uncertainty only. The eligible-count row is monotone by construction and is reported for completeness rather than as a test. Rotterdam estimates are descriptive: that cohort shows a severe lack of empirical overlap inside the full protocol.")); }

/* ---------- 2 ---------- */
add(H2("Repeated splits are not independent replicates"));
if (has(DP.colon)) {
  add(P("Resampling the cohort around the whole split procedure separates algorithmic stability from population uncertainty. Because a bootstrap resample contains duplicate copies of a patient, the inner split is taken over unique patient identifiers so that no patient contributes to both halves; an earlier version of this analysis split the resampled rows directly, which allowed copies of one patient to fall on opposite sides, and the numbers below are the corrected ones. Correcting it narrowed rather than widened the intervals."));
  add(P("With " + DP.colon.B + " outer resamples and " + DP.colon.R_IN + " inner splits each, the standard deviation of the colon probability of a lower out-of-sample hazard ratio across resamples is " + f(DP.colon.se_lower,3) + ". Of that, " + f(DP.colon.mc_lower,3) + " is the inner Monte Carlo component implied by " + DP.colon.R_IN + " splits and " + f(DP.colon.between_lower,3) + " is the outer-sampling component obtained by subtracting it. The naive across-split standard error is " + f(DP.colon.naive_lower,4) + ", so the outer-sampling component alone is " + f(DP.colon.ratio_between_lower,0) + " times it. The 95% percentile interval runs from " + f(DP.colon.ci_lower[0],2) + " to " + f(DP.colon.ci_lower[1],2) + "; in Rotterdam, from " + f(DP.rott.ci_lower[0],2) + " to " + f(DP.rott.ci_lower[1],2) + ". We use percentile rather than accelerated intervals because the statistic is a proportion of proportions and the acceleration estimate is unstable at this outer count." + (NS.colon && NS.colon.lower && isFinite(NS.colon.lower.conv) ? " Recomputing every interval from half the outer resamples moves the endpoints by at most " + f(Math.max.apply(null, ['more','lower','front_hr','front_rm','front_hrM'].map(k => (NS.colon[k]||{}).conv||0).concat(['hr0.1','rm0.1'].map(k => (NS.colon[k]||{}).conv||0))),3) + " in colon, which is the resolution at which these intervals should be read." : "") + ""));
  add(P("These intervals cover most of the range: the point estimates of 0.270 and 0.497 are properties of these datasets rather than estimates of how often the procedure would succeed elsewhere, and an in-sample evaluation on a single cohort has access to neither source of variability. The eligibility probability is better determined, interval [" + f(DP.colon.ci_more[0],2) + ", " + f(DP.colon.ci_more[1],2) + "] in colon, as one expects of a quantity that is monotone by construction."));
}

/* ---------- 3 ---------- */
add(H2("No unconditional data requirement exists, and the reason is not sample size"));
add(P("With the scoring set fixed at 100 000 patients, the eligibility promise was kept at every fitting size, from 0.950 at 300 patients to 1.000 at 20 000. The effect-estimate promise rose from 0.273 to 0.997 over the same range, crossing 0.8 near 3000 and reaching 0.937 at 5167. At the population level the rule was correct: it identified the diluting criterion and its protocol lowered the hazard ratio from 0.6637 to 0.6327 while raising the eligible count from 55 179 to 78 847. The observed colon values sit close to this curve — 0.270 against a predicted 0.279 at 309 fitting patients, and 0.336 against 0.339 at 433 — but the interval around those observed values, from the previous section, spans most of the unit interval, so the agreement has almost no power to discriminate and we draw no confirmation from it."));
if (has(FA.n_med)) {
  const FX = NUM.fixedn ? NUM.fixedn.cells : null;
  add(P("That curve belongs to one generating mechanism, and across the resolution-IV factorial the threshold does not transfer: in " + FA.n_right + " of 16 scenarios the crossing lay above the largest fitting size evaluated and in one below the smallest. We therefore report the success probability at fixed fitting sizes, which every scenario supplies."));
  if (FX) {
    add(table(
      ["Fitting patients", "Effect modification concentrated: median [min, max]", "Spread over five criteria: median [min, max]"],
      [["600",   f(FX.n600.conc_med,2)   + " [" + f(FX.n600.conc_lo,2)   + ", " + f(FX.n600.conc_hi,2)   + "]", f(FX.n600.diff_med,2)   + " [" + f(FX.n600.diff_lo,2)   + ", " + f(FX.n600.diff_hi,2)   + "]"],
       ["2 000", f(FX.n2000.conc_med,2)  + " [" + f(FX.n2000.conc_lo,2)  + ", " + f(FX.n2000.conc_hi,2)  + "]", f(FX.n2000.diff_med,2)  + " [" + f(FX.n2000.diff_lo,2)  + ", " + f(FX.n2000.diff_hi,2)  + "]"],
       ["6 000", f(FX.n6000.conc_med,2)  + " [" + f(FX.n6000.conc_lo,2)  + ", " + f(FX.n6000.conc_hi,2)  + "]", f(FX.n6000.diff_med,2)  + " [" + f(FX.n6000.diff_lo,2)  + ", " + f(FX.n6000.diff_hi,2)  + "]"],
       ["18 000",f(FX.n18000.conc_med,2) + " [" + f(FX.n18000.conc_lo,2) + ", " + f(FX.n18000.conc_hi,2) + "]", f(FX.n18000.diff_med,2) + " [" + f(FX.n18000.diff_lo,2) + ", " + f(FX.n18000.diff_hi,2) + "]"]],
      [2600, 3400, 3360],
      "Table 2. Probability of a lower out-of-sample hazard ratio at fixed fitting-cohort size, across all sixteen factorial scenarios, eight per column. Monte Carlo standard error is at most 0.071. No threshold is estimated, so nothing is censored and no scenario is excluded."));
  }
  add(P("The spread across scenarios at any fixed size is large — the standard deviation of the success probability is " + f(NUM.fixedn.cells.n2000.sd_all,2) + " at 2000 fitting patients and " + f(NUM.fixedn.cells.n6000.sd_all,2) + " at 6000, on a scale bounded by one — and an interval-censored regression cannot resolve it, because the arrangement factor completely separates the design (Table S2b)."));
  add(P("We withdraw a claim made in the first revision, that the threshold is more variable in events and effective sample size than in patients: that was computed over the six scenarios in which a threshold was observable, a selected subset. Binning all sixteen by each currency instead, the three are indistinguishable — " + f(NUM.fixedn.spread_patients,2) + ", " + f(NUM.fixedn.spread_events,2) + " and " + f(NUM.fixedn.spread_ess,2) + ". None is more portable, and none determines the answer."));
  add(P("The 0.80 reliability target is a convention borrowed from power calculations and nothing depends on it: at 0.70 and 0.90 the median located threshold is 2000 and 4811 fitting patients and the separation between the two arrangements is unchanged (Table S2b)."));
}
add(P("The factorial contrasted modification concentrated in one criterion with modification spread over five, and describing the result as being about concentration turned out to be wrong. In that design the per-criterion coefficient was simply divided, so the diffuse arm also had a weaker DILUTING coefficient — 0.128 against 0.32 — and dilution is what the rule must detect, since relaxation can lower the hazard ratio only by dropping a criterion that selects patients who benefit less. Concentration and detection strength were confounded."));
if (CN && CN.A_dil1_enr1) {
  const g = k => CN[k].rows.map(r => f(r.p_lower,2)).join(" / ");
  add(P("A separate sweep separates them, holding the total modification fixed at 0.85 and varying only its arrangement. With the diluting coefficient fixed at 0.30, success at 600, 2000, 6000 and 18 000 fitting patients runs " + g("A_dil1_enr1") + " with the enrichment in one criterion, " + g("B_dil1_enr2") + " split over two and " + g("C_dil1_enr4") + " split over four. Spreading the enrichment never hurts, and at 6000 patients it helps by 0.21 (95% interval 0.08 to 0.34) and 0.20 (0.07 to 0.33) — so it is not, as we first wrote, without effect. Splitting the DILUTION goes the other way at every size: the same total with the diluting signal halved across two criteria gives " + g("D_dil2_enr1") + ", differences from the first arrangement of −0.19, −0.26, −0.39 and −0.42, every interval excluding zero."));
  add(P("Two cautions belong with that comparison. The arrangements hold the full-protocol hazard ratio exactly equal, since under the full protocol the treated bonus is the sum of the coefficients, which the design fixes; they do not hold the ATTAINABLE improvement equal. On a 120 000-patient evaluation set the best subset reaches 0.6698 against a full-protocol 0.6900 in the three arrangements that concentrate the dilution, a gap of 0.0203, and 0.6803 in the one that splits it, a gap of 0.0098. Splitting the dilution halves the prize as well as the coefficient, and the two cannot be separated, because the attainable gap is itself determined by how the dilution is distributed. Arrangements that concentrate it present both a larger coefficient and a larger prize and are correspondingly easier; the sweep does not isolate the coefficient."));
add(P("The second is that a raw coefficient is unlikely to be the general governing quantity at all: the same coefficient on a criterion retaining 90% of a cohort and on one retaining 30% carries different information, and detectability must also depend on prevalence, correlation among criteria, retained events, censoring and weight variability. A criterion-specific signal-to-noise ratio — the population Shapley value of the diluting criterion over the standard deviation of its estimate — is the more plausible candidate, and one comparison is suggestive: the three arrangements that concentrate the dilution share an identical diluting coefficient of 0.30 and near-identical population Shapley values, so the coefficient cannot separate them at all, while their signal-to-noise ratios (1.39, 1.51, 1.73) do order their observed success (0.58, 0.79, 0.78). Four arrangements cannot establish anything, and we offer this as the direction a general answer would take rather than as one."));
add(P("What survives is the consequence for planning. Whatever the right summary turns out to be, it is a property of the effect modification present, which is the quantity the analysis exists to estimate. Positivity, logical implication and interaction leverage can all be computed before any outcome is examined; the strength of the diluting signal cannot. So a data requirement cannot be read off cohort size, event count or effective sample size alone. It can be stated conditionally, on an assumed minimum diluting signal, exactly as a conventional power calculation is stated on an assumed minimum clinically relevant effect — and Table 2 read as a family of conditional reliability curves is that statement. What does not exist is an unconditional threshold, and it was one of those that we offered in the previous version."));
}
add(FIG("fig_trainsize.png", 618, 260,
  "Figure 3. Left: probability that each promise is kept by fitting-cohort size in the single-mechanism simulation, scoring set fixed at 100 000, with Monte Carlo intervals. The observed cohort points carry the outer-bootstrap intervals from the nested resampling, which span most of the unit interval; their apparent agreement with the simulated curve has little discriminating power and we draw no confirmation from it. Right: the probability that the rule recovers the exactly correct criterion set."));

/* ---------- 4 ---------- */
add(H2("Below the threshold the selected protocol can be slightly worse than the original"));
if (RC && RC.length) {
  const A0 = RC[0], AZ = RC[RC.length-1];
  add(P("Exact recovery of the criterion set rose from " + f(A0.exact) + " at " + f0(A0.n) + " fitting patients to " + f(AZ.exact) + " at " + f0(AZ.n) + ", but that is an unnecessarily strict standard when several protocols perform almost identically. The softer measures move monotonically: Hamming distance fell from " + f(A0.hamming,2) + " criteria to " + f(AZ.hamming,2) + ", Jaccard similarity rose from " + f(A0.jaccard) + " to " + f(AZ.jaccard) + ", false retention fell from " + f(A0.false_retain) + " to " + f(AZ.false_retain) + " and false relaxation from " + f(A0.false_relax) + " to " + f(AZ.false_relax) + ". Over-relaxation is the error that persists."));
  add(P("Regret needs defining before it is read. Ours is on the log hazard-ratio scale: the difference between the population log hazard ratio under the selected protocol and under the subset that minimises it, both evaluated on the fixed 100 000-patient scoring set. It is a single-objective measure that ignores eligible count, safety and every other clinical consideration, and because different protocols target different populations a larger regret means further from the lowest attainable hazard ratio rather than worse for a patient. The full protocol has a regret of its own, which is what makes the two comparable. In this generating model the rule's population limit set coincides with the minimising subset, so its asymptotic regret is zero; the Shapley-sign rule carries no general guarantee of reaching the global optimum when interactions are present and we claim this for this scenario only. Regret falls from " + f(A0.regret,4) + " at " + f0(A0.n) + " fitting patients to " + f(AZ.regret,4) + " at " + f0(AZ.n) + ". The full protocol's regret is " + f(NUM.recovery_full_regret,4) + ". The two cross near a thousand fitting patients: below that, the protocol the rule produces sits slightly further from the lowest attainable hazard ratio than the full protocol does. Read narrowly — as a statement about this one generating model and this one objective — it means the expected outcome for a small cohort is not a smaller improvement but a marginally worse position on that objective, applied to a larger group of patients. It is not a claim that the resulting protocol is clinically worse, which would need the other objectives weighed alongside it."));
}

/* ---------- 5 ---------- */
add(H2("Confounding moves the threshold, and unmeasured confounding hides itself"));
add(P("Correctly adjusted confounding lowered the curve throughout: at 5167 fitting patients the probability fell from 0.937 to 0.808, so roughly twice the sample is needed for a given reliability."));
add(P("The third arm is the more consequential result and requires care with language. Because all three arms share one outcome model, the true causal contrast is identical in all three by construction; what differs is the population limit of the weighted estimator under each adjustment. Omitting one confounder returned the reliability curve to randomised levels — 0.936 at 5167 against 0.937 — which might easily be read as reassurance. The estimator's population limit for the gap between protocols rose to 0.0408 from 0.0310, 32% larger, with the whole hazard ratio displaced from 0.664 to 0.757. Meanwhile the probability of recovering the correct criterion set fell from 0.280 to 0.116. The procedure appeared equally reliable while its selection was in fact less accurate, because the quantity it was detecting had itself been inflated by bias."));
add(P([R("Observing that the method performs well on real-world data therefore does not by itself indicate that adjustment was adequate. A useful sensitivity analysis compares the estimated gap under richer and poorer adjustment and expects it to shrink as adjustment improves — but that expectation holds only when the added variables are plausibly confounders. Adding an instrument can amplify residual bias"), CITE("myers2011"), R(" and adding a collider or mediator can create it, so the direction of travel is a warning worth heeding among substantively defensible adjustment sets, not a test that settles the question.")]));
add(FIG("fig_confound.png", 618, 250,
  "Figure 4. Three treatment-assignment mechanisms sharing one outcome model, with Monte Carlo intervals. Left: correctly adjusted confounding lowers the curve; omitting one confounder returns it to randomised levels. Centre: the population limit of the estimated gap is 32% larger under unmeasured confounding — the true causal gap is identical in all three arms. Right: correct selection meanwhile falls by more than half."));

/* ---------- 6 ---------- */
add(H2("Why the hazard ratio is the fragile leg"));
add(P("Under proportional hazards with the conditional hazard ratio fixed at 0.6 in every stratum, a criterion defined on the prognostic covariate changes no individual's relative benefit, yet its Shapley value on the log hazard ratio grew monotonically with prognostic strength, from −0.0008 with no heterogeneity to −0.066 at the strongest setting, while the marginal hazard ratio drifted from 0.599 to 0.804. The value at zero heterogeneity is the falsification point and the artefact vanished there. The restricted mean difference also moved, and in the opposite direction: it fell from 0.664 in the whole cohort to 0.599 in the selected group at the weakest setting and from 0.425 to 0.322 at the strongest, so its Shapley value is negative throughout. That is the expected direction and it corresponds to a real fact — a lower-risk group has less absolute survival to gain, because more of it survives the horizon regardless of treatment. The hazard-ratio movement corresponds to no fact of either kind, which is the concrete reason a lower hazard ratio must not be read as a better estimate."));
add(FIG("fig_sim.png", 618, 250,
  "Figure 5. Non-collapsibility as a dose–response. The conditional hazard ratio is 0.6 in every stratum at every point on these curves, so the criterion changes no individual's relative benefit; the Shapley value on the log hazard ratio nonetheless grows with prognostic strength and vanishes where there is no heterogeneity to collapse over."));

/* ---------- 7 ---------- */
add(H2("Pairwise interactions here are attenuated, not absent"));
add(P([R("The plate plot, adapted here from network meta-analysis"), CITE("ren2026"), R(", displays both estimands in one panel (Figure 6). Leverage is signed: positive correlation raises the joint eligibility rate above the product of the marginals, and once it rises far enough the factor can become negative, meaning the contrast flips sign rather than vanishing. Magnitude therefore measures attenuation. In colon the median magnitude was 0.013 and the maximum 0.086, with no pair of 36 above 0.10 and 35 of 36 below 0.05; in Rotterdam the median was 0.022, four pairs exceeded 0.10 and 26 of 36 fell below 0.05.")]));
add(P("The consequence is a power statement, not a structural one. A global permutation test on the colon interaction matrix returned p = 0.26 on the hazard ratio and 0.21 on the restricted mean, and no main effect survived multiplicity adjustment on either estimand. Because the contrast in these cells is attenuated by a factor of order 0.01 to 0.09, those nulls carry little information about effect modification: they bound what could have been detected at this attenuation and sample size and nothing more. The one class of cells about which a null is definitive is the logically implied pair, where the contrast is exactly zero and which the implication detector removes before testing."));
if (NUM.coverage) {
  const C = NUM.coverage;
  add(P("Against known truth over " + C.reps + " replicates at n = 1500, the bias-corrected and accelerated interval attained " + f(C.bca_null,3) + " coverage (Monte Carlo SE " + f(C.se_null,3) + ") for a null interaction, against a nominal 0.95, while the percentile interval over-covered at " + f(C.pct_null,3) + ". Since most cells of a real interaction matrix are null and their false-positive behaviour determines what gets reported, that is the comparison that matters. For a genuinely non-null interaction both under-covered, at " + f(C.bca_planted,3) + " and " + f(C.pct_planted,3) + " (Monte Carlo SE " + f(C.se_planted,3) + "). We recommend at least 1000 bootstrap replicates and 50 jackknife groups, and treating intervals for large interactions as mildly anticonservative."));
} else {
  add(P("[Coverage results pending.]"));
}
if (RR) {
  add(P("Because what advantage the point estimates show appears on the hazard ratio and not on absolute benefit, we asked what happens if the rule selects on the restricted mean difference instead — retaining every criterion whose RMST Shapley value is positive. The two rules are close to different procedures: they agree on the criterion set in " + pct(PR.colon.same_set) + " of colon splits and " + pct(PR.rott.same_set) + " of Rotterdam splits, and in colon the RMST rule admits " + f0(PR.colon.n_rmrule) + " patients against the hazard-ratio rule\'s " + f0(PR.colon.n_rule) + " and the full protocol\'s " + f0(PR.colon.n_full) + "."));
  add(P("Out of sample the RMST-selected variant exceeded the full protocol\'s restricted mean difference in " + pct(PR.colon.rmrule_greater) + " of colon splits against " + pct(PR.colon.greater) + " for the published rule, and reached a lower hazard ratio in " + pct(PR.colon.rmrule_lower) + " against " + pct(PR.colon.lower) + "." + (NS.colon && NS.colon.rmrule_greater ? " Carried through the same patient-level resampling these are " + pct(PR.colon.rmrule_greater) + ", interval [" + f(NS.colon.rmrule_greater.ci[0],2) + ", " + f(NS.colon.rmrule_greater.ci[1],2) + "], and " + pct(PR.colon.rmrule_lower) + ", interval [" + f(NS.colon.rmrule_lower.ci[0],2) + ", " + f(NS.colon.rmrule_lower.ci[1],2) + "]; the agreement rate itself has interval [" + f(NS.colon.rm_same.ci[0],2) + ", " + f(NS.colon.rm_same.ci[1],2) + "]." : "") + " We therefore do not claim that switching the estimand gains nothing. What the data show is that the two decompositions select almost different criterion sets, that the point estimates for the RMST-selected variant are not higher on either estimand, and that the uncertainty around them is wide enough that an investigator whose endpoint is absolute benefit should not expect the switch to deliver it, nor conclude from these cohorts that it cannot."));

}
if (NUM.horizon) {
  const HZc = NUM.horizon.colon, HZr = NUM.horizon.rott;
  const rng = (T, k) => f(Math.min.apply(null, T.map(r => r[k])),3) + " to " + f(Math.max.apply(null, T.map(r => r[k])),3);
  add(P("The horizon matters for both of these comparisons and was not justified in the previous version. The restricted mean must be taken at a time inside the observed follow-up of both arms of every candidate protocol, or subsets are not compared on the same scale; we used " + f0(NUM.horizon.tau_colon) + " days in colon and " + f0(NUM.horizon.tau_rott) + " days in Rotterdam, at which at least " + pct(NUM.horizon.risk_colon) + " and " + pct(NUM.horizon.risk_rott) + " of patients in either arm are still under observation; the next horizon we tried drops that figure sharply. Repeating the selection comparison at four horizons per cohort, the two decompositions agree on the criterion set in " + rng(HZc, "same") + " of colon splits and " + rng(HZr, "same") + " of Rotterdam splits, with mean Jaccard similarity of " + rng(HZc, "jac") + " and " + rng(HZr, "jac") + " respectively. The disagreement between the two estimands is therefore a property of the estimands rather than of the particular horizon, but the exact agreement rate is horizon-dependent and should be reported with the horizon attached."));
  add(P("The horizon also changes the sign of the absolute-benefit comparison, which we had not looked for. In colon the mean out-of-sample restricted mean difference at the shortest horizon we tried is " + f(HZc[0].rmF,1) + " days for the full protocol against " + f(HZc[0].rm1,1) + " for the published rule and " + f(HZc[0].rm2,1) + " for the RMST-selected variant, so both relaxed protocols are ahead; at the horizon used in the main analysis the ordering reverses, " + f(HZc[2].rmF,1) + " against " + f(HZc[2].rm1,1) + " and " + f(HZc[2].rm2,1) + ". A statement that relaxation does or does not improve absolute benefit is therefore not well posed without the horizon, and our own main-text figures are the pessimistic end of the range we examined. We report the horizon everywhere and do not generalise beyond it."));
}

add(FIG("fig2_plate3.png", 440, 522,
  "Figure 6. The criteria plate plot for colon. Upper triangle, pairwise interaction on the log hazard ratio; lower triangle, on the restricted mean difference; diagonal, per-criterion main effects on both estimands, shaded by the fraction of the cohort the criterion excludes. Light hatching marks cells whose leverage is below 0.05 in magnitude — 35 of 36 here — and dense hatching cells that are arithmetic identities. A full-page version is Supplementary Figure S2."));

/* ================= DISCUSSION ================= */
add(H1("Discussion"));
add(P("Data-driven relaxation admits more patients, and it is worth being precise about what that shows. The rule retains a subset of the criteria, so the eligible set can only grow, and the probability reported for this promise measures how often a binding criterion is removed. Scored against all 512 subsets on the held-out half, the rule's choice is almost never on the empirical eligible-count-versus-hazard-ratio frontier, though simulation shows that frontier is itself optimistic and the honest reading is a distance from an optimistic oracle rather than a measure of inefficiency. Matched on eligible count, its hazard-ratio advantage has an interval containing one half, and on the absolute-benefit estimand the point estimate sits below one half. So the rule is not optimising the trade-off between the two promises, and whether it has any advantage at equal inclusiveness is a question these cohorts cannot settle — neither of which a comparison against the full protocol alone can show."));
add(P("What a wider eligible population is worth clinically is a separate question no outcome model answers, and criteria are not all of a kind: those encoding safety, tolerability, feasibility or pharmacology should be designated non-relaxable before the procedure runs rather than left to a hazard ratio to adjudicate."));
add(P("Whether the effect-estimate improvement is attainable depends on something that cannot be checked before the analysis, but that does not make planning impossible. Across the factorial the success probability varies by roughly 0.34 in standard deviation at every fixed sample size, and grouping scenarios by events or by effective sample size rather than by patients does not reduce that spread at all — a claim we made in the previous revision and withdraw here, because it was computed only over the scenarios in which a threshold happened to be observable. We are not able to name the quantity that does govern the requirement. A sentence in the previous revision named the magnitude of the largest diluting effect-modification coefficient, and we withdraw it: our own results do not support it. Arranging the same total modification differently is not neutral — spreading the enrichment raised success by 0.21 [0.08, 0.34] at 6000 — and halving the diluting coefficient also roughly halves the attainable gap, so in that design the coefficient and the size of the prize move together and cannot be separated. What can be said is weaker and, we think, still useful: the requirement depends on the strength of the diluting signal relative to the noise at the fitting size, and that strength is what the analysis exists to estimate, so no requirement in patients, events or effective sample size can be given unconditionally. This is the ordinary position of a power calculation, whose sample size also depends on an effect size not yet observed. A criterion-specific signal-to-noise ratio — the population Shapley value of the most diluting criterion over the standard deviation of its estimate at the fitting size — is the most promising candidate we have tried: across twelve simulated cells it orders success better than the fitting size does (Spearman " + (NUM.snr_curve ? f(NUM.snr_curve.sp_snr,2) + " against " + f(NUM.snr_curve.sp_n,2) : "—") + "), but twelve cells cannot establish a governing quantity and the two indices are correlated by construction, so we report it as a direction rather than an answer (Supplementary Table S4b). What we can rule out is an unconditional threshold of the kind we ourselves offered in the previous version. Table 2 should accordingly be read as a sensitivity analysis across arrangements at fixed fitting sizes, not as a design curve to read a requirement from. The result also separates cleanly what an investigator can check beforehand — empirical overlap inside the full protocol, logical implication, interaction leverage — from what they cannot."));
add(P("For small cohorts the regret comparison adds a further caution: the protocol the rule produces sits slightly further from the lowest attainable hazard ratio than the original does. That is a single-objective statement about one generating model, not a claim of clinical inferiority."));
add(P("The unmeasured-confounding arm is the finding we would most want carried forward. Residual confounding inflated the quantity being detected and thereby made the procedure appear more reliable while its selection became less accurate, which runs against the usual intuition that a clear signal is reassuring. The recommendation that follows — compare adjustment sets and expect the gap to shrink — is a heuristic with real exceptions and should be used among substantively defensible sets rather than as a test."));
add(P("Rotterdam is a cautionary example of a different kind. Chemotherapy there went almost exclusively to younger, premenopausal women, so within the restrictive full protocol there is very little overlap and no specification we tried restores balance — exactly the check we argue should come first. Restriction does not create it; overlap was flat in the number of criteria applied in both cohorts."));
add(P("Three by-products may be useful independently. Interaction leverage is a closed-form quantity requiring no outcome data that says how far a pair's interaction is attenuated by the eligibility rates alone; we have corrected the claim made for it — low leverage is attenuation rather than structural invisibility — and derived the coefficient for three interaction forms, all multiples of (1−q)(1−q) under independence, exact for the both-criteria structure and approximate for the other two. The implication detector removes cells that are arithmetic identities, the only cells genuinely uninformative regardless of sample size. And carrying both estimands makes visible where a criterion's relative and absolute effects disagree, a substantive question that should be settled on clinical grounds rather than by a software default."));
add(P("Several limitations bound these conclusions. The criteria were constructed from available covariates rather than transcribed from protocols, so this demonstrates a general property rather than evaluating any trial, and neither cohort is the database used in the original work. The factorial is resolution IV, so two-factor interactions are aliased in pairs; the criterion-count factor spans only 6 against 8, because exhaustive enumeration costs 2^p evaluations per replicate; and propensity overlap, weight variability, missingness and model misspecification are represented crudely or not at all. All simulated quantities depend on their generating models. The absolute-benefit column depends on an analyst choice of horizon, and in colon its sign flips across a plausible range of that choice. The leverage expressions are derived for three specific interaction forms."));

add(H1("Conclusions"));
add(P("Relaxing trial eligibility criteria from data widens the eligible population, but that widening follows largely from the structure of the rule, and scored against the subsets attainable on held-out patients the rule's choice is rarely near the empirical eligible-count-versus-hazard-ratio frontier, an object that is itself optimistic. Whether it contributes anything at matched inclusiveness is not resolved by cohorts of this size; the point estimates favour it on the hazard ratio and not on absolute benefit, and a variant selecting on absolute benefit instead chooses almost entirely different criteria, with point estimates no higher on either estimand and intervals too wide to settle the matter. How much data that contribution requires cannot be read from patients, events or effective sample size alone: it depends on the strength of the diluting signal, which is the quantity the analysis exists to discover. It can be stated conditionally on an assumed minimum such signal, as a power calculation is stated on an assumed minimum effect; what does not exist is an unconditional threshold. Incomplete confounding adjustment can make the procedure appear more successful while its selection is less accurate, so apparent success on real-world data should not be taken as evidence of adequate adjustment. What an investigator can establish beforehand is narrower than we previously suggested — empirical overlap inside the full protocol, logical implication among criteria, and interaction leverage — and it does not include whether the effect-estimate promise is within reach."));
};
