module.exports = function (M) {
const {add, P, H1, H2, R, table} = M;

/* ---------------- background ---------------- */
add(H1("Background"));
add(P("Overly restrictive eligibility criteria are a recognised barrier to trial accrual and to the generalisability of trial results. Around 80% of patients with advanced non-small-cell lung cancer do not meet the criteria of the trials conducted in that disease, and criteria are frequently inherited from legacy protocols rather than justified for the trial at hand. Regulators and professional bodies have both called for criteria to be broadened where they can be broadened safely."));
add(P("A computational answer to that call has emerged: emulate the trial in a real-world cohort, vary the criteria in silico, and let the data indicate which ones can be dropped. Trial Pathfinder is the most influential instance. It encodes a protocol's criteria as programmatic filters, estimates the treatment effect under every combination, and attributes to each criterion a Shapley value quantifying its average contribution to the hazard ratio. Criteria with a negative Shapley value are retained and the rest relaxed. Applied to ten advanced non-small-cell lung cancer trials, the procedure more than doubled the eligible pool while lowering the hazard ratio of overall survival by 0.05 on average. Follow-up work has applied the same framework to lung cancer in a Chinese real-world database, to asthma and chronic obstructive pulmonary disease, and to multiple myeloma, and a scoping review has begun to map the area."));
add(P("Two features of this literature motivated the present work. First, every reported result is in-sample: the criteria are selected and the resulting protocol is scored in the same patients. Selection and evaluation on one dataset is the classical setting for optimistic bias, and its magnitude here is unknown. Second, the procedure makes two promises that are reported as a pair — more patients, and a better effect estimate — but there is no reason for the two to require the same amount of data. Enrolling more patients follows from relaxing almost any criterion; improving the effect estimate requires relaxing the right ones."));
add(P("A third issue is specific to the outcome scale. The hazard ratio is non-collapsible: restricting a cohort changes the marginal hazard ratio even when the conditional treatment effect is identical in every stratum. A criterion-selection method built on the hazard ratio therefore inherits a component of movement that carries no information about who benefits. This has been discussed at length in the survival-analysis literature but has not been examined in the context of criteria selection."));
add(P("We set out to answer three questions. Does the published rule keep its promises when the protocol it produces is scored on patients that had no part in choosing it? If not, is that a property of the rule or of the amount of data available to fit it? And what, if anything, can an investigator check before running such an analysis to know whether their cohort can support it?"));

/* ---------------- methods ---------------- */
add(H1("Methods"));

add(H2("Cohorts"));
add(P("Both cohorts are individual-level datasets distributed with the R package survival, so every result below can be reproduced without a data application. The first is the adjuvant colon-cancer trial of levamisole and fluorouracil, restricted to the Lev+5FU and observation arms (n = 619, 304 treated, 291 deaths). Treatment assignment is randomised, which makes the mapping from criteria to hazard ratio free of confounding and provides a clean bench for validating estimators. The second is the Rotterdam breast-cancer registry (n = 2982, 580 receiving chemotherapy, 1272 deaths), an observational cohort that plays the role real-world data plays in the original work."));
add(P("Nine eligibility criteria were constructed for each cohort from the available covariates: for colon, bounds on age, absence of obstruction, perforation and adherence to adjacent organs, differentiation grade, extent of local spread, interval since surgery and nodal burden; for Rotterdam, bounds on age, nodal status and count, tumour size, receptor positivity and enrolment year. These are plausible criteria for methodological illustration, not the trials' protocol text. Each set was checked to contain no logical implications (see below) and retains 176 (28.4%) and 419 (14.1%) of the respective cohorts when all criteria are applied, which is within the range real protocols retain."));

add(H2("Value function and estimands"));
add(P("For a subset S of criteria we define a value function returning three quantities on the cohort S selects: the log hazard ratio from an inverse-probability-of-treatment-weighted Cox model, the difference in restricted mean survival time to a fixed horizon tau, and the log of the eligible count. Patients with a missing value on a criterion are not filtered by that criterion, following the original convention. The horizon tau is fixed across all subsets so that the restricted means remain comparable; we used 5 years for colon and 7 years for Rotterdam."));
add(P("Both benefit estimands are carried in parallel rather than one being chosen. The hazard ratio preserves comparability with the existing literature; the restricted mean survival time difference is collapsible, so a change in it corresponds to a real change in expected benefit for the selected population. Where the two disagree, the disagreement is informative and cannot be resolved by preference."));
add(P("Logarithms are taken because the Shapley axioms presuppose an additive value function, and both the hazard ratio and the eligible count are ratio-scale quantities whose additive scale is the logarithm. The original work applies the Shapley decomposition to the hazard ratio directly, under which the efficiency axiom holds only approximately."));

add(H2("Shapley main effects and pairwise interactions"));
add(P([R("For p criteria there are 2"), R("p", {sup:true}), R(" subsets. Where p is at most about 16 these can be enumerated exhaustively, so main effects and interactions are computed exactly rather than by Monte Carlo, and the efficiency axiom can be verified to machine precision. We use the Shapley value for main effects and the Grabisch–Roubens index for pairwise interactions, the latter being the natural extension to pairs and, being symmetric, the natural object for a square display.")]));

add(H2("Two diagnostics that need no outcome data"));
add(P("The first detects criteria that logically imply one another. If criterion i implies criterion j then the cohort selected by S union {i,j} is identical to that selected by S union {i} for every S, so the pair's four-point difference collapses to minus the marginal contribution of j. Such a cell is an arithmetic identity rather than evidence and must be removed from any test family."));
add(P("The second asks whether a criterion pair could show an interaction at all. Under the clinically natural structure in which extra benefit accrues only to patients meeting both criteria, the four-point difference driving the interaction is proportional to"));
add(P("L(i,j)  =  1  −  p(ij)/p(i)  −  p(ij)/p(j)  +  p(ij)", {align: M.AlignmentType.CENTER, i: true, after: 160}));
add(P("where p(i) and p(j) are the marginal eligibility rates and p(ij) the joint rate. We call this the interaction leverage. It depends only on eligibility rates and is therefore computable before any outcome is examined. It falls sharply as criteria become permissive: two independent criteria each retaining 85% of a cohort have leverage 0.022, whereas two retaining 45% have leverage 0.303. A criterion pair with negligible leverage cannot exhibit a pairwise interaction of this form however strong the underlying effect modification, so a null interaction must not be read as evidence that none exists."));

add(H2("Out-of-sample evaluation of the selection rule"));
add(P("The published rule was implemented exactly as described: compute the Shapley value of every criterion on the log hazard ratio, retain those with a negative value, relax the rest. Patients were split at random into a fitting set and a scoring set. The rule was applied to the fitting set alone and the protocol it produced was scored on the scoring set, alongside the original full protocol, on all three quantities. This was repeated 500 times for colon and 400 times for Rotterdam, at fitting fractions of 0.5 and 0.7."));
add(P("An earlier version of this analysis compared, instead, the protocol minimising the hazard ratio against the protocol maximising the restricted mean difference, both selected by exhaustive search. That comparison is unsound in two ways and we report it only as a caution. First, the winner is guaranteed: the protocol maximising an estimand in a sample wins on that estimand there by construction, so the observed difference measures the optimisation gap, not a difference between estimands. Second, and more fundamentally, the selection is unstable: in the colon cohort a single estimand reproduced its own choice of protocol in 3.6% of resample pairs, less often than the two estimands agreed with each other (10.6%). An exhaustive argmax over 512 candidates is also a far more aggressive selection than the published rule performs, so a failure there would not have implicated the rule."));

add(H2("Simulation"));
add(P("Sample splitting confounds two things: how much data the rule has to find the right criteria, and how precisely the resulting protocol can be scored. To separate them we generated data from a known model, fixed the scoring set at 100 000 patients so that scoring noise was negligible, and varied only the fitting size across 300, 1000, 3000, 5167 and 20 000 patients with 300 replicates each. The value 5167 is the average per-trial cohort size in the original work. The generating model gave the rule something real to find: eight criteria on eight covariates, of which three genuinely modified the treatment effect — two enriching for benefit and one diluting it — on a background of strong prognostic heterogeneity so that non-collapsibility was operative. At the population level the rule correctly identified the diluting criterion, so any failure at finite sample is a sample-size phenomenon and not a defect of the rule."));
add(P("Three arms sharing one outcome model then separated the effect of the treatment-assignment mechanism. In arm A assignment was randomised. In arm B assignment depended on three covariates and the propensity model included all of them. In arm C assignment depended on the same covariates but the propensity model omitted one, representing unmeasured confounding. Because the outcome model is common to all three arms, the target the rule is trying to find is identical and only the assignment mechanism and the adequacy of adjustment differ."));
add(P("A separate simulation examined non-collapsibility in isolation. Under a proportional-hazards model in which the conditional hazard ratio equals exp(log 0.6) in every stratum of a prognostic covariate Z, a criterion of the form Z at or below its median changes no individual's relative benefit. We swept the prognostic strength from zero upward; at zero there is no heterogeneity to collapse over and the artefact must vanish, which provides a falsification point."));

add(H2("Uncertainty"));
add(P("Intervals are bias-corrected and accelerated bootstrap intervals, the acceleration constant estimated by a grouped jackknife. Significance bands are obtained by interval inversion — the smallest level at which the interval excludes zero — rather than a constructed p-value, and are then adjusted across the pair family by the Benjamini–Hochberg procedure after removing logically determined cells. A global permutation test on the whole interaction matrix provides a single-degree-of-freedom alternative to many marginal tests. Interval coverage was validated against known truth in 120 replicates at n = 1500."));

add(H2("Implementation"));
add(P([R("The 2"), R("p", {sup:true}), R(" enumeration is evaluated once per bootstrap replicate, so per-subset cost governs feasibility. Because the model is always one binary covariate with weights, we solve the weighted Cox partial likelihood by Newton–Raphson directly and compute the weighted restricted mean from the Kaplan–Meier estimator directly, avoiding formula parsing and model-frame construction. The full cohort is sorted by time once so that logical subsetting preserves the ordering. These kernels agree with the survival package to 9.4 × 10"), R("−13", {sup:true}), R(" for the Cox coefficient and exactly for the restricted mean, and are about eighteen times faster, which is what makes exhaustive enumeration with a 2000-replicate bootstrap affordable. Everything is available as the R package trialplate, with 16 correctness assertions covering the efficiency axiom, matrix symmetry, the null-player axiom, agreement of exact enumeration with permutation Monte Carlo, the implication detector, seed reproducibility and the leverage identity.")]));
};
