const d = require('docx');
const {Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel} = d;
const fs = require('fs');
const NUM = JSON.parse(fs.readFileSync("/home/claude/repo/analysis/out/numbers.json","utf8"));
const FA = NUM.factorial || {}, RB = NUM.random || {}, DP = NUM.dependence || {}, E = NUM.efficiency;
const f = (x,k=3) => (x===null||x===undefined||Number.isNaN(x)) ? "[pending]" : Number(x).toFixed(k);
const f0 = x => f(x,0);
const pct = (x,k=1) => (x===null||x===undefined) ? "[pending]" : (100*Number(x)).toFixed(k)+"%";

const body = [];
const add = (...x) => x.forEach(e => Array.isArray(e) ? body.push(...e) : body.push(e));
const P = (t,o={}) => new Paragraph({spacing:{after:o.after??130, line:290},
  alignment: AlignmentType.JUSTIFIED, indent: o.ind?{left:340}:undefined,
  children:[new TextRun({text:t, size:o.size??21, font:"Calibri", italics:o.i, bold:o.b, color:o.color})]});
const H1 = t => new Paragraph({heading:HeadingLevel.HEADING_1, spacing:{before:300,after:140},
  children:[new TextRun({text:t, font:"Calibri"})]});
const Q = t => new Paragraph({spacing:{before:230, after:90}, indent:{left:340},
  border:{left:{style:d.BorderStyle.SINGLE, size:12, color:"9DB2C6", space:12}},
  children:[new TextRun({text:t, size:20, font:"Calibri", italics:true, color:"3A4A5C"})]});
const A = t => P(t, {});
const WHERE = t => P(t, {size:19, color:"55606B", after:190});

add(new Paragraph({spacing:{after:60}, children:[new TextRun({
  text:"Response to the reviewer", bold:true, size:30, font:"Calibri"})]}));
add(P("Manuscript: What data-driven relaxation of trial eligibility criteria can and cannot promise: out-of-sample validation and the sample size it requires", {size:20, color:"555555", after:260}));
add(P("We are grateful for a review that identified two points on which we were mistaken and several more where we were claiming more than our design supports. Three of the changes below alter the paper's conclusions rather than its wording: the eligibility promise is now presented as monotone by construction, the sample-size guidance has been replaced by a factorial estimate in three currencies, and the Rotterdam cohort has been reclassified as descriptive after we found a positivity violation we had not looked for. We answer each point in turn and say where the change is.", {after:240}));

add(H1("Major comments"));

/* ---- 1 ---- */
add(Q("1. Increased eligibility is largely guaranteed by construction."));
add(A("Accepted in full; this was the most consequential point in the review. The data-driven protocol retains a subset of the criteria, so its eligible set is a superset and the count cannot fall. We verified this empirically as well as by argument: across 500 colon splits the minimum difference in eligible count was exactly zero and never negative. Decomposing the reported probability shows precisely what the reviewer says it is — the rule removed at least one criterion in 99.0% of splits, in a further 1.2% the removals did not bind on the scoring half, and the difference, 0.978, is the number we had been reporting as a validated benefit."));
add(A("We have therefore stopped treating it as a validation endpoint. The claim that inclusiveness alone is a sufficient argument for the approach is removed from the abstract, results, discussion and conclusions. In its place we added a test with content: for every split we now also draw random relaxations that remove exactly as many criteria as the rule did, and score them on the same held-out half. The rule need not beat random relaxation on eligible count, since that quantity is monotone in the number of removals alone, but it should beat it on the hazard ratio if the selection is doing work."
  + (RB.colon ? " The rule showed no advantage on eligible count (" + pct(RB.colon.p_more_rand) + " in colon, " + pct(RB.rott.p_more_rand) + " in Rotterdam) and in the registry cohort admitted fewer patients than random relaxation of the same size — 442 against 664 on average. It did perform better than random relaxation on the hazard ratio (" + pct(RB.colon.p_hr_rand) + " and " + pct(RB.rott.p_hr_rand) + "), though the margin in the randomised cohort is slight. This suggests the rule's contribution lies in the effect estimate rather than in accrual. The distinction does not appear when the only comparison drawn is against the full protocol, which is the comparison we had reported." : " Results are in Table 1 and the Results section.")));
add(A("We have also added the discussion of non-relaxable criteria that the reviewer asks for: criteria encoding safety, tolerability, treatment feasibility or pharmacology should be designated non-relaxable before the procedure runs, because no outcome model can adjudicate them, and we say so in the Discussion."));
add(WHERE("Where: Methods, “Target estimand, and what each promise is a claim about”; new analysis script analysis/random_benchmark.R; Results §1; Table 1 note; Discussion ¶1; Conclusions."));

/* ---- 2 ---- */
add(Q("2. A lower hazard ratio is not necessarily an improved effect estimate."));
add(A("Accepted. Relaxing criteria changes the population and therefore the estimand, so the two protocols are not two estimators of one quantity. We have added an explicit estimand subsection at the head of the Methods defining the target under a protocol as the marginal contrast in the population that protocol selects, and we now use “more favourable estimated contrast” wherever we previously wrote “improved effect estimate”. Claims about estimation accuracy are confined to the simulation, where truth is known; in the two cohorts we report only whether the contrast moved favourably out of sample."));
add(A("The reviewer's observation that our own non-collapsibility result makes this distinction essential is exactly right, and we have moved that argument forward so it appears before the empirical results rather than after them."));
add(WHERE("Where: Methods, new subsection; every occurrence in Results and Discussion; Abstract."));

/* ---- 3 ---- */
add(Q("3. The proposed sample-size thresholds are not sufficiently general."));
add(A("Accepted, and this is the largest addition. We have replaced the single-mechanism threshold with a 2⁴ resolution-IV fractional factorial in the six factors the reviewer names — number of candidate criteria, protocol restrictiveness, magnitude and sparsity of effect modification, event rate, allocation ratio, and assignment mechanism with adjustment — sixteen scenarios in all. In each, the crossing point is located by interpolation on a ladder of fitting sizes with a bootstrap interval over replicates."));
if (FA.n_med) {
  const BY = FA.by || {};
  add(A("The result changed our conclusion rather than qualifying it, and we are glad to have run it. In " + FA.n_right + " of the sixteen scenarios the probability never reached 0.80 anywhere on a ladder running to 18 000 fitting patients. The censoring is not scattered: of the eight scenarios in which effect modification is concentrated in one criterion, " + BY.nmod_2.complete + " located a threshold, at a median of " + f0(BY.nmod_2.med_n) + " patients; of the eight in which the same total modification is spread across five criteria, " + BY.nmod_5.complete + " did, under any combination of the other five factors. No other factor comes close to separating the design this way."));
  add(A("The guidance we offered was therefore imprecise, and also directed at a less central question than we had supposed. The prior question is not how many patients a cohort holds but whether the protocol contains a criterion concentrating enough differential benefit to be identified at all; where it does not, no realistic database size helps. The sentence “roughly 3000 patients under randomisation and about twice that under confounding” is gone from the Conclusions, and where a threshold exists we now report the range (" + f0(FA.n_min) + " to " + f0(FA.n_max) + ", median " + f0(FA.n_med) + ") with the scenario-by-scenario table in Supplementary Table S2."));
  add(A("On re-expressing the threshold in information rather than patient count, which the reviewer suggested and we expected to work: it does not. The coefficient of variation across scenarios is " + f(FA.cv_n,2) + " in patients, " + f(FA.cv_ev,2) + " in full-protocol events and " + f(FA.cv_ess,2) + " in effective sample size — more variable, not less. We report all three and withdraw the recommendation rather than defend it. We think the negative result is worth stating because the intuition behind it is a natural one."));
  add(A("One scenario was censored at the other end, with the probability already above 0.80 at the smallest size evaluated. It needs careful interpretation and we now flag it: there the full protocol retained about 13 events, so its own hazard ratio is the imprecise quantity and almost any wider protocol improves on it. A high probability of a lower hazard ratio may therefore reflect a comparator too small to estimate well rather than a well-chosen relaxation."));
} else { add(A("[Factorial results are reported in Results §3 and Supplementary Table S2.]")); }
add(A("Three honest limitations remain and are stated in the Discussion. A resolution-IV design estimates main effects cleanly but aliases two-factor interactions in pairs. Several factors on the reviewer's list — propensity-score overlap, weight variability, missingness, model misspecification — are represented crudely or not at all, and we say which. And the criterion-count factor is tested over 6 against 8 rather than a wider range, because exhaustive enumeration costs 2^p value-function evaluations per replicate and a wider contrast was not affordable; we state the levels used rather than implying broader coverage."));
add(A("One further point emerged while building this. A scenario in which every effect-modifying criterion enriches benefit has no attainable threshold at any sample size, because relaxation can only lower the hazard ratio if some retained criterion selects patients who benefit less. That is a property of the protocol, not of the estimator. We ensure every factorial scenario contains a diluting criterion and state the caveat."));
add(WHERE("Where: Methods, “Simulation, and the factorial over the threshold”; Results §3; Supplementary Table S2; Discussion ¶3; Conclusions. New script analysis/factorial_threshold.R."));

/* ---- 4 ---- */
add(Q("4. Repeated sample splits are statistically dependent."));
add(A("Accepted, and the correction is a substantial one. We have added nested resampling: the cohort is bootstrapped, the whole split procedure is run inside each resample, and the spread across resamples gives population-level uncertainty."
  + (DP.colon ? " For the probability of a lower out-of-sample hazard ratio in colon, the across-split standard error is about 0.011 while the across-cohort standard deviation is " + f(DP.colon.se_lower,3) + " — roughly twenty-five times larger. The 95% interval runs from " + f(DP.colon.ci_lower[0],2) + " to " + f(DP.colon.ci_lower[1],2) + ", and in Rotterdam from " + f(DP.rott.ci_lower[0],2) + " to " + f(DP.rott.ci_lower[1],2) + ". These cohorts cannot distinguish a rule that keeps the promise nine times in ten from one that rarely keeps it. We report both standard errors and note that the point estimates are properties of these datasets." : "")));
add(A("On interpretation, we now state explicitly that the split proportions are conditional algorithmic stability within these datasets rather than the probability of success in a new cohort, and we use that language throughout. On the mechanics the reviewer asks about: splitting is at the patient level and is now stratified by treatment arm and event status, so every fitting half carries both arms and a comparable number of events; this is stated in the Methods and implemented in the code."));
add(WHERE("Where: Methods, “Out-of-sample evaluation, and the dependence between splits”; Results §2; new script analysis/split_dependence.R."));

/* ---- 5 ---- */
add(Q("5. The statement concerning Shapley efficiency appears incorrect."));
add(A("The reviewer is right and we thank them for catching it. Efficiency holds exactly for any real-valued characteristic function computed by exact enumeration and does not require a logarithm. We verified this numerically on the colon cohort: the Shapley values sum to the total to within " + E.err_log.toExponential(1) + " on the log scale and " + E.err_hr.toExponential(1) + " on the hazard-ratio scale. The sentence claiming approximate efficiency on the hazard-ratio scale has been deleted."));
add(A("What we should have said, and now do, is that the scale determines which aggregate is decomposed. On the log scale the total is log(HR under the full protocol / HR under no criteria) = " + f(E.tot_log,4) + ", the multiplicative change; on the hazard-ratio scale it is the arithmetic difference " + f(E.tot_hr,4) + ". For a ratio measure the multiplicative change is the interpretable aggregate, which is our reason for the log scale — an interpretive argument, not an axiomatic one, and now labelled as such. We also note the one thing that does break efficiency numerically, which is an infeasible subset whose value is undefined and drops silently out of the sum; we ridge-penalise to avoid it and report the count."));
add(A("The package's correctness assertions have been extended to check efficiency on both scales, so this cannot regress."));
add(WHERE("Where: Methods, “Value function, and the scale on which the decomposition runs”; package tests."));

/* ---- 6 ---- */
add(Q("6. The observational analysis requires substantially more detail."));
add(A("Accepted, and acting on it changed one of our conclusions. We now report the propensity specification in full (main-effects logistic on the recorded covariates, no interactions or splines, unstabilised weights, truncation at 0.05/0.95), confirm that the model is re-estimated inside every subset, every split and every bootstrap replicate rather than fitted once and reused, and give balance, overlap, truncation counts and effective sample size for both cohorts."));
add(A("Doing so indicated that the Rotterdam analysis does not support a causal reading. Within the full protocol, 132 of 419 propensities sit at the truncation bound, six of eight covariates remain above 0.10 standardised difference after weighting (maximum 0.251), and the effective sample size is 155, 37% of nominal. The cause is near-deterministic assignment: of 116 full-protocol patients aged 55 to 70, twelve received chemotherapy, and 175 of 203 treated patients are premenopausal against 45 of 216 controls. We tried the obvious repairs — splines, stabilised weights, common-support trimming — and none works; splines make balance worse. This indicates a positivity violation, and we now report the Rotterdam hazard ratios as descriptive and rest the causal reading on the randomised cohort and on simulation. We would not have looked without this comment."));
add(A("We also asked whether restriction itself degrades overlap, since the full protocol is the most restrictive cohort in the analysis. It does not: sweeping all 512 subsets in each cohort, the weighted effective-sample-size fraction is flat in the number of criteria applied and Rotterdam's imbalance mildly improves with restriction. The positivity problem is a property of that cohort, present before any criterion is applied. We report this negative result because we had expected the opposite."));
add(A("On missingness: we compare the original not-filtered convention with missing-as-ineligible and with imputation. We also report, so that no reader assumes the convention was load-bearing, that only one criterion in one cohort has any missingness at all (colon differentiation, 2.1%) and Rotterdam has none. The check is demonstrated rather than decisive here, and we say that."));
add(A("On the shrinkage diagnostic, the reviewer's qualification is correct and we have adopted it. Adding an instrument can amplify residual bias and adding a collider or mediator can create it, so the direction of travel across adjustment sets is a warning worth heeding among substantively defensible sets, not a test that settles the question. The Discussion now says this rather than the stronger claim we made."));
add(WHERE("Where: Methods, “Cohorts, criteria and weighting”; Results §5; Discussion ¶4–5; new scripts analysis/cohort_tables.R, analysis/ps_sensitivity.R, analysis/overlap_vs_restriction.R, analysis/missing_sens.R; Supplementary Table S1."));

/* ---- 7 ---- */
add(Q("7. The unmeasured-confounding simulation uses potentially misleading terminology."));
add(A("Accepted. Because the three arms share one outcome model, the true causal contrast is identical in all three by construction, and what we labelled the “true population gap” is the large-sample limit of the weighted estimator under the stated adjustment. We now call it exactly that, reserve “true causal gap” for the quantity that does not move, and have relabelled the figure axis and the table accordingly."));
add(A("Separating the two clarified the result rather than weakening it, and we thank the reviewer for it. We can now say that the estimator's population limit rises 32% under unmeasured confounding while the causal truth is unchanged, which is the whole point. We also noticed, in re-examining these arms, a result we had not previously drawn out: under unmeasured confounding the rule's probability of recovering the exactly correct criterion set falls from 0.280 to 0.116 while the apparent reliability is unchanged at 0.936 against 0.937. The procedure appears equally reliable while its selection is in fact less accurate. This is now the third panel of Figure 4."));
add(WHERE("Where: Results §5; Figure 4 and its caption; Table 2; Discussion ¶4."));

/* ---- 8 ---- */
add(Q("8. Claims about interaction leverage are overstated."));
add(A("Accepted. “Structurally unidentifiable” is now reserved for cells whose four-point contrast is exactly zero, which is the logical-implication case and a property of the criteria alone. Low leverage is described as attenuation by a known factor, and we state that detectability of an attenuated contrast still depends on effect magnitude, outcome variance and sample size like any other test."));
add(A("We have also done the derivation the reviewer asks for. The published expression is specific to the form in which extra benefit accrues only to patients meeting both criteria. We derived the coefficient for benefit under either criterion and for benefit under exactly one, and verified all three by simulation. Under independent criteria at a common rate q they are (1−q)², −(1−q)² and −2(1−q)² respectively: multiples of the same quantity, so permissiveness attenuates all three. Simulation confirms the both-criteria coefficient to a few per cent and the other two to within 10–30%, the gap arising because the derivation ignores reweighting when the bonus reaches a large share of the cohort. We report that accuracy honestly and note that other forms will have other coefficients."));
add(A("Finally we no longer use the non-significant tests in the two cohorts as confirmation of anything. Because the contrast in those cells is attenuated by a factor of order 0.01 to 0.09, the null results bound what could have been detected at this attenuation and sample size and nothing more. They are reported for completeness with no conclusion drawn."));
add(WHERE("Where: Methods, “Interaction leverage: attenuation, not invisibility”; Results §7; Discussion ¶6; new script analysis/leverage_forms.R."));

/* ---- 9 ---- */
add(Q("9. Simulation transparency and reproducibility are currently insufficient."));
add(A("Accepted. Supplementary Text S1 now gives the complete generating equations and every parameter value for each simulation, including eligibility rates, effect-modification coefficients, prognostic strength, baseline hazard, censoring, allocation and the propensity model used to assign treatment in the confounded arms."));
add(A("On the calibration question, which is the sharpest form of this point: no parameter of the generating model was estimated from either cohort. All were set a priori. The agreement between the simulated curve and the observed colon values is therefore a prediction rather than a calibration. We now also state the limits of that evidence — it is a single agreement at one point, and the same curve does not describe Rotterdam, which sits below it. We would rather present it as one hit and one miss with an explanation than as a validation."));
add(A("We have additionally made the manuscript itself reproducible in a way it was not before. Every number quoted in the text is exported by the analysis scripts into a machine-readable file that the manuscript build reads, so no figure in the prose can drift from the code that produced it. We also found while preparing this revision that the scripts generating Figures 3–5 had not been committed; they are now, which is how the Monte Carlo error bars and the accessible palette below were added."));
add(A("The repository is complete and will be public with an archived DOI at acceptance; we can supply an anonymous reviewer link immediately on request."));
add(WHERE("Where: Supplementary Text S1; analysis/export_numbers.R; analysis/figures.R; repository README."));

add(H1("Minor comments"));
add(A("1. The 0.80 reliability threshold. It is a convention borrowed from conventional power and we now say so, and report the crossing at 0.70 and 0.90 alongside it so that a reader can see how much the choice moves the answer."));
add(A("2. Softer recovery measures. Added: Hamming distance, Jaccard similarity, false-retention and false-relaxation rates, and regret against the best attainable protocol. All move monotonically with fitting size and false relaxation is the error that persists. The regret measure led to a result we would not otherwise have found: because the full protocol has a regret of its own (0.0544 on this model), the two can be compared, and below roughly a thousand fitting patients the rule's protocol sits slightly further from the optimum than the protocol it was intended to improve. Below the threshold the outcome is therefore a little worse than the starting protocol rather than simply an absent improvement, and we now report this in the Results and Discussion. New script analysis/recovery_metrics.R."));
add(A("3. Coverage replicates. Increased well beyond 120, with Monte Carlo standard errors reported. The undercoverage for non-null interactions persists and is now estimated more precisely rather than explained away."));
add(A("4. Criteria table. Supplementary Table S1 gives every criterion in both cohorts with its definition, marginal eligibility, missingness, events and patients retained by arm, and the full pairwise correlation matrix. Maximum off-diagonal correlation is 0.25 in colon and 0.57 in Rotterdam."));
add(A("5. Uncertainty bands and Monte Carlo error. Added to Figures 3 and 4 as Wilson intervals, and to every simulated probability in the text and tables."));
add(A("6. Figure 6 legibility. A full-page version is provided as Supplementary Figure S2."));
add(A("7. Table 2 pagination. Fixed; the table is now kept whole on one page."));
add(A("8. Colourblind accessibility. All figures redrawn in the Okabe–Ito palette, with line type and plotting symbol varying alongside hue so that no comparison depends on colour alone."));
add(A("9. Literature review. The placeholder is removed. We have not attempted the systematic accounting that would license a claim about the whole literature, so we no longer make one: the text now says that the evaluations we are aware of are in-sample and states that limitation explicitly rather than asserting universality."));
add(A("10. Placeholders. Authors, affiliations, declarations, funding, repository URL and DOI are for the corresponding author to complete before submission and are flagged in the manuscript."));

add(new Paragraph({spacing:{before:300}, children:[new TextRun({
  text:"Two of these comments — on the efficiency axiom and on the eligibility comparison — identified errors rather than omissions, and a third prompted us to examine Rotterdam's overlap, which we should have checked ourselves and which changed how we report that cohort. The paper is better for all three, and we are grateful for the care the review took.",
  size:21, font:"Calibri", italics:true})]}));

const doc = new Document({sections:[{properties:{page:{size:{width:12240,height:15840},
  margin:{top:1080,bottom:1080,left:1180,right:1180}}}, children: body}]});
Packer.toBuffer(doc).then(b => { fs.writeFileSync("response_to_reviewer.docx", b);
  console.log("written", b.length, "bytes"); });
